<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-BR" xml:lang="pt-BR"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Marco Antônio e Matheus Villela">

<title>Relatório 02 - Aula prática 02</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-efbb37e9afcc02144ebbc7afd12a776f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Sumário</h2>
   
  <ul>
  <li><a href="#introdução" id="toc-introdução" class="nav-link active" data-scroll-target="#introdução"><span class="header-section-number">1</span> 📌 Introdução</a></li>
  <li><a href="#objetivo-geral" id="toc-objetivo-geral" class="nav-link" data-scroll-target="#objetivo-geral"><span class="header-section-number">2</span> 🎯 Objetivo geral</a>
  <ul class="collapse">
  <li><a href="#objetivos-específicos" id="toc-objetivos-específicos" class="nav-link" data-scroll-target="#objetivos-específicos"><span class="header-section-number">2.1</span> Objetivos específicos</a></li>
  </ul></li>
  <li><a href="#metodologia" id="toc-metodologia" class="nav-link" data-scroll-target="#metodologia"><span class="header-section-number">3</span> ⚙️ Metodologia</a>
  <ul class="collapse">
  <li><a href="#etapas-de-desenvolvimento" id="toc-etapas-de-desenvolvimento" class="nav-link" data-scroll-target="#etapas-de-desenvolvimento"><span class="header-section-number">3.1</span> 📋 Etapas de desenvolvimento</a></li>
  <li><a href="#etapa-conclusiva-script-final" id="toc-etapa-conclusiva-script-final" class="nav-link" data-scroll-target="#etapa-conclusiva-script-final"><span class="header-section-number">3.2</span> 🏁 Etapa conclusiva — Script final</a></li>
  </ul></li>
  <li><a href="#fundamentação-teórica" id="toc-fundamentação-teórica" class="nav-link" data-scroll-target="#fundamentação-teórica"><span class="header-section-number">4</span> 📚 Fundamentação teórica</a></li>
  <li><a href="#resultados-e-discussão" id="toc-resultados-e-discussão" class="nav-link" data-scroll-target="#resultados-e-discussão"><span class="header-section-number">5</span> 🔍 Resultados e Discussão</a>
  <ul class="collapse">
  <li><a href="#questão-1-importação-dos-dados" id="toc-questão-1-importação-dos-dados" class="nav-link" data-scroll-target="#questão-1-importação-dos-dados"><span class="header-section-number">5.1</span> Questão 1 — Importação dos dados</a></li>
  <li><a href="#questão-2-dimensões-da-base" id="toc-questão-2-dimensões-da-base" class="nav-link" data-scroll-target="#questão-2-dimensões-da-base"><span class="header-section-number">5.2</span> Questão 2 — Dimensões da base</a></li>
  <li><a href="#questão-3-estrutura-da-base-de-dados" id="toc-questão-3-estrutura-da-base-de-dados" class="nav-link" data-scroll-target="#questão-3-estrutura-da-base-de-dados"><span class="header-section-number">5.3</span> Questão 3 — Estrutura da base de dados</a></li>
  <li><a href="#questão-4-resumo-estatístico-da-base-de-dados" id="toc-questão-4-resumo-estatístico-da-base-de-dados" class="nav-link" data-scroll-target="#questão-4-resumo-estatístico-da-base-de-dados"><span class="header-section-number">5.4</span> Questão 4 — Resumo estatístico da base de dados</a></li>
  <li><a href="#questão-5-classificação-das-variáveis" id="toc-questão-5-classificação-das-variáveis" class="nav-link" data-scroll-target="#questão-5-classificação-das-variáveis"><span class="header-section-number">5.5</span> Questão 5 — Classificação das variáveis</a></li>
  <li><a href="#questão-6-valores-ausentes-na-base" id="toc-questão-6-valores-ausentes-na-base" class="nav-link" data-scroll-target="#questão-6-valores-ausentes-na-base"><span class="header-section-number">5.6</span> Questão 6 — Valores ausentes na base</a>
  <ul class="collapse">
  <li><a href="#investigação-dos-erros-de-preenchimento-e-padronização" id="toc-investigação-dos-erros-de-preenchimento-e-padronização" class="nav-link" data-scroll-target="#investigação-dos-erros-de-preenchimento-e-padronização"><span class="header-section-number">5.6.1</span> Investigação dos erros de preenchimento e padronização</a></li>
  </ul></li>
  <li><a href="#questão-7-valores-potencialmente-incompatíveis" id="toc-questão-7-valores-potencialmente-incompatíveis" class="nav-link" data-scroll-target="#questão-7-valores-potencialmente-incompatíveis"><span class="header-section-number">5.7</span> Questão 7 — Valores potencialmente incompatíveis</a></li>
  </ul></li>
  <li><a href="#considerações-finais" id="toc-considerações-finais" class="nav-link" data-scroll-target="#considerações-finais"><span class="header-section-number">6</span> 🧠 Considerações finais</a></li>
  <li><a href="#referências" id="toc-referências" class="nav-link" data-scroll-target="#referências"><span class="header-section-number">7</span> 📖 Referências</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">
<div class="logos" style="display: flex; justify-content: center; align-items: center; height: 200px; gap: 20px;">
  <a href="https://ufsj.edu.br">
    <img src="imagens/ufsj.png" width="220px">
  </a>
  <a href="https://ufsj.edu.br/defim">
    <img src="imagens/defim.png" width="220px">
  </a>
</div>

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Relatório 02 - Aula prática 02</h1><button type="button" class="btn code-tools-button dropdown-toggle" id="quarto-code-tools-menu" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi"></i> Código</button><ul class="dropdown-menu dropdown-menu-end" aria-labelelledby="quarto-code-tools-menu"><li><a id="quarto-show-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Mostrar o código</a></li><li><a id="quarto-hide-all-code" class="dropdown-item" href="javascript:void(0)" role="button">Esconder o código</a></li><li><hr class="dropdown-divider"></li><li><a id="quarto-view-source" class="dropdown-item" href="javascript:void(0)" role="button">Ver o código fonte</a></li></ul></div></div>
<p class="subtitle lead"><a href="https://bendeivide.github.io/courses/eait/" target="_blank">Estatística Aplicada a Inovações Tecnológicas (UFSJ)</a> <br> <a href="https://bendeivide.github.io" target="_blank">Prof.&nbsp;Ben Dêivide (DEFIM/CAP/UFSJ)</a></p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor</div>
    <div class="quarto-title-meta-contents">
             <p>Marco Antônio e Matheus Villela </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Data de Publicação</div>
    <div class="quarto-title-meta-contents">
      <p class="date">29/08/2026, 17:20</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introdução" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> 📌 Introdução</h1>
<p>No <strong>controle tecnológico do concreto</strong>, a qualidade das decisões técnicas depende diretamente da confiabilidade dos dados coletados em campo e em laboratório. Contudo, na prática profissional, é comum que bases de dados apresentem inconsistências, como <strong>valores ausentes, erros de digitação, padronização inadequada de categorias e registros incompatíveis com a realidade física do concreto</strong>. Esses problemas, quando não tratados adequadamente, podem comprometer as análises estatísticas e levar a interpretações equivocadas.</p>
<p>Esta atividade simula uma situação real em que o engenheiro recebe uma <strong>base de dados bruta contendo 100 registros e 10 variáveis relacionadas ao concreto</strong>. Utilizando a linguagem <strong>R, com ênfase nos recursos do Base R</strong>, o trabalho consiste em <strong>inspecionar, diagnosticar, limpar e explorar os dados</strong>, transformando informações inconsistentes em dados confiáveis para auxiliar na tomada de decisão no contexto da <strong>Engenharia Civil</strong>.</p>
</section>
<section id="objetivo-geral" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> 🎯 Objetivo geral</h1>
<p>Inspecionar, diagnosticar, limpar e explorar uma base de dados do <strong>controle tecnológico do concreto</strong> utilizando o <strong>R (Base R)</strong>, transformando dados brutos e inconsistentes em informações confiáveis para a <strong>tomada de decisão técnica no âmbito da Engenharia Civil</strong>.</p>
<section id="objetivos-específicos" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="objetivos-específicos"><span class="header-section-number">2.1</span> Objetivos específicos</h2>
<ul>
<li><p><strong>Conhecer a estrutura da base</strong>, identificando o número de observações, variáveis, tipos de dados e valores ausentes.</p></li>
<li><p><strong>Diagnosticar problemas</strong>, como erros de digitação, separadores decimais incorretos, categorias despadronizadas e valores incompatíveis com o contexto da Engenharia Civil.</p></li>
<li><p><strong>Padronizar e limpar os dados</strong>, corrigindo variáveis qualitativas e quantitativas, tratando valores ausentes e criando uma versão limpa da base.</p></li>
<li><p><strong>Explorar os dados tratados</strong> por meio de estatísticas descritivas e análises agrupadas por obra, tipo de concreto e idade.</p></li>
<li><p><strong>Criar variáveis derivadas com interpretação técnica</strong>, como resistência relativa, classificação de desempenho e indicador de desempenho acima da média.</p></li>
<li><p><strong>Aplicar funções do Base R</strong>, como <code>split()</code>, <code>lapply()</code>, <code>sapply()</code>, <code>apply()</code>, <code>aggregate()</code>, <code>for</code> e <code>if</code>, para o processamento e a análise dos dados.</p></li>
<li><p><strong>Responder questões práticas da Engenharia Civil</strong>, como a comparação de desempenho entre blocos e a relação entre diferentes variáveis do concreto.</p></li>
<li><p><strong>Documentar e justificar as decisões de limpeza e análise</strong>, garantindo maior rastreabilidade e reprodutibilidade dos procedimentos realizados.</p></li>
<li><p><strong>Desenvolver um script organizado e comentado</strong> que execute todo o fluxo de trabalho, desde a inspeção inicial até a geração de estatísticas e variáveis derivadas.</p></li>
</ul>
</section>
</section>
<section id="metodologia" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> ⚙️ Metodologia</h1>
<p>A metodologia adotada neste trabalho consiste no <strong>processamento completo de uma base de dados do controle tecnológico do concreto</strong>, utilizando a linguagem <strong>R</strong>, com ênfase nos recursos disponíveis no <strong>Base R</strong>.</p>
<p>O fluxo de trabalho segue uma sequência lógica composta pelas etapas de:</p>
<ol type="1">
<li><strong>Importação dos dados</strong>;</li>
<li><strong>Inspeção inicial da base</strong>;</li>
<li><strong>Diagnóstico de inconsistências</strong>;</li>
<li><strong>Limpeza e padronização dos dados</strong>;</li>
<li><strong>Tratamento dos valores ausentes</strong>;</li>
<li><strong>Exploração estatística</strong>;</li>
<li><strong>Criação de variáveis derivadas</strong>;</li>
<li><strong>Aplicação de funções de processamento</strong>;</li>
<li><strong>Interpretação dos resultados sob a perspectiva da Engenharia Civil</strong>.</li>
</ol>
<p>As etapas foram organizadas em <strong>35 questões</strong>, que orientam o desenvolvimento progressivo da atividade.</p>
<section id="etapas-de-desenvolvimento" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="etapas-de-desenvolvimento"><span class="header-section-number">3.1</span> 📋 Etapas de desenvolvimento</h2>
<p><strong>Questão 01 — Importação dos dados</strong></p>
<p>Importe a base de dados para o R e atribua-a ao objeto <code>dados</code>, verificando a correta importação.</p>
<p><strong>Questão 02 — Dimensões da base</strong></p>
<p>Determine as dimensões da base, identificando o número de <strong>observações (linhas)</strong> e <strong>variáveis (colunas)</strong>.</p>
<p><strong>Questão 03 — Estrutura da base</strong></p>
<p>Apresente a estrutura completa da base utilizando a função <code>str()</code> e analise detalhadamente o resultado obtido.</p>
<p><strong>Questão 04 — Resumo estatístico</strong></p>
<p>Gere um resumo estatístico das variáveis com a função <code>summary()</code> e identifique informações que merecem atenção.</p>
<p><strong>Questão 05 — Classificação das variáveis</strong></p>
<p>Classifique as variáveis em <strong>quantitativas</strong> e <strong>qualitativas</strong>, com base na estrutura apresentada pelo R.</p>
<p><strong>Questão 06 — Valores ausentes</strong></p>
<p>Verifique a existência de <strong>valores ausentes (<em>missing values</em>)</strong>, identificando a quantidade, as variáveis e as observações afetadas.</p>
<p><strong>Questão 07 — Valores incompatíveis</strong></p>
<p>Verifique valores incompatíveis com o contexto da Engenharia Civil nas variáveis <code>idade_dias</code>, <code>resistencia_mpa</code>, <code>abatimento_mm</code>, <code>densidade_kg_m3</code>, <code>relacao_a_c</code> e <code>absorção_agregado_pct</code>, criando códigos para a localização das observações problemáticas.</p>
<p><strong>Questão 08 — Erros de digitação</strong></p>
<p>Localize possíveis <strong>erros de digitação</strong> e apresente os registros completos das observações afetadas.</p>
<p><strong>Questão 09 — Padronização da variável <code>obra</code></strong></p>
<p>Verifique a padronização das categorias da variável <code>obra</code> e identifique possíveis inconsistências.</p>
<p><strong>Questão 10 — Padronização da variável <code>tipo_concreto</code></strong></p>
<p>Verifique a padronização das categorias da variável <code>tipo_concreto</code> e identifique categorias que representam o mesmo tipo de concreto com <strong>grafias diferentes</strong>.</p>
<p><strong>Questão 11 — Reavaliação dos tipos</strong></p>
<p>Reavalie os tipos das variáveis após a identificação dos problemas e reflita sobre como <strong>um único valor digitado incorretamente pode alterar a interpretação de uma variável inteira pelo R</strong>.</p>
<p><strong>Questão 12 — Cópia da base original</strong></p>
<p>Crie uma cópia da base original chamada <code>dados_limpos</code> e discuta a importância de <strong>preservar a base original</strong> durante o processo de tratamento dos dados.</p>
<p><strong>Questão 13 — Correção das variáveis qualitativas</strong></p>
<p>Corrija os problemas encontrados nas variáveis qualitativas, <strong>padronizando suas categorias</strong>.</p>
<p><strong>Questão 14 — Conversão das variáveis quantitativas</strong></p>
<p>Converta para o tipo adequado as variáveis que deveriam ser quantitativas e verifique se a conversão foi realizada corretamente.</p>
<p><strong>Questão 15 — Tratamento dos valores ausentes</strong></p>
<p>Identifique os valores ausentes e discuta os procedimentos mais adequados para cada situação, considerando <strong>exclusão, substituição, manutenção do <code>NA</code> ou consulta à fonte original</strong>. Justifique tecnicamente as decisões adotadas.</p>
<p><strong>Questão 16 — Reavaliação da base limpa</strong></p>
<p>Reavalie a estrutura (<code>str()</code>) e o resumo (<code>summary()</code>) da base limpa e compare os resultados obtidos com aqueles observados na <strong>base original</strong>.</p>
<p><strong>Questão 17 — Resistência média</strong></p>
<p>Calcule a <strong>resistência média à compressão</strong> dos corpos de prova globalmente e por bloco da obra, tipo de concreto e idade do corpo de prova.</p>
<p><strong>Questão 18 — Maior e menor resistência média</strong></p>
<p>Identifique o bloco da obra que apresenta a <strong>maior e a menor resistência média</strong>, apresentando os códigos utilizados para essa identificação.</p>
<p><strong>Questão 19 — Resistência por classe de concreto</strong></p>
<p>Calcule a resistência média para cada classe de concreto (<strong>C25, C30, C35 e C40</strong>) e identifique a classe que apresenta a <strong>maior resistência média</strong>.</p>
<p><strong>Questão 20 — Aplicação da função <code>aggregate()</code></strong></p>
<p>Utilize a função <code>aggregate()</code> para obter a média das variáveis <code>resistencia_mpa</code>, <code>cimento_kg_m3</code>, <code>relacao_a_c</code>, <code>abatimento_mm</code> e <code>densidade_kg_m3</code> para cada tipo de concreto e interprete os resultados.</p>
<p><strong>Questão 21 — Resistência relativa</strong></p>
<p>Crie a variável <code>resistencia_relativa</code>, representando a razão entre a <strong>resistência observada</strong> e uma <strong>resistência de referência associada à classe do concreto</strong>, e explique como a referência foi definida.</p>
<p><strong>Questão 22 — Classificação do desempenho</strong></p>
<p>Crie a variável <code>classificacao</code>, classificando os corpos de prova segundo um critério relacionado à resistência, definindo e justificando tecnicamente os critérios utilizados.</p>
<p><strong>Questão 23 — Desempenho acima da média</strong></p>
<p>Crie a variável <code>acima_media</code>, indicando se a resistência do corpo de prova está <strong>acima ou abaixo da resistência média de seu respectivo tipo de concreto</strong>, utilizando os valores <code>TRUE</code> ou <code>FALSE</code>.</p>
<p><strong>Questão 24 — Aplicação da função <code>split()</code></strong></p>
<p>Utilize a função <code>split()</code> para dividir a base de dados de acordo com a variável <code>tipo_concreto</code> e conte o <strong>número de observações em cada grupo</strong>.</p>
<p><strong>Questão 25 — Aplicação da função <code>lapply()</code></strong></p>
<p>Utilizando a estrutura criada com <code>split()</code>, calcule a <strong>resistência média de cada tipo de concreto</strong> utilizando a função <code>lapply()</code>.</p>
<p><strong>Questão 26 — Aplicação da função <code>sapply()</code></strong></p>
<p>Repita a operação utilizando <code>sapply()</code> e explique a diferença entre os resultados produzidos por <code>lapply()</code> e <code>sapply()</code>.</p>
<p><strong>Questão 27 — Aplicação da função <code>apply()</code> para médias</strong></p>
<p>Selecione as variáveis quantitativas relacionadas às propriedades do concreto e utilize a função <code>apply()</code> para calcular a <strong>média de cada variável</strong>.</p>
<p><strong>Questão 28 — Aplicação da função <code>apply()</code> por observação</strong></p>
<p>Utilize a função <code>apply()</code> para obter, para cada observação, uma <strong>medida resumo envolvendo as variáveis quantitativas selecionadas</strong> e discuta a interpretação física dessa medida.</p>
<p><strong>Questão 29 — Aplicação de <code>for</code> e <code>if</code></strong></p>
<p>Utilizando <code>for</code> e <code>if</code> — <strong>sem utilizar <code>ifelse()</code></strong> — percorra as 100 observações e identifique os corpos de prova cuja resistência está acima da <strong>resistência média de sua respectiva classe de concreto</strong>.</p>
<p><strong>Questão 30 — Abordagem vetorizada</strong></p>
<p>Repita a questão anterior utilizando uma <strong>abordagem vetorizada</strong> e compare as duas soluções quanto à simplicidade, legibilidade e eficiência, justificando sua análise.</p>
<p><strong>Questão 31 — Comparação entre blocos</strong></p>
<p>Verifique descritivamente a afirmação:</p>
<blockquote class="blockquote">
<p><strong>“Os concretos utilizados no Bloco C apresentam desempenho superior aos utilizados nos demais blocos.”</strong></p>
</blockquote>
<p>Realize a análise <strong>sem utilizar teste de hipótese</strong>.</p>
<p><strong>Questão 32 — Consumo de cimento e resistência</strong></p>
<p>Investigue a afirmação:</p>
<blockquote class="blockquote">
<p><strong>“Quanto maior o consumo de cimento, maior tende a ser a resistência do concreto.”</strong></p>
</blockquote>
<p>Identifique as variáveis que devem ser analisadas conjuntamente para avaliar essa relação.</p>
<p><strong>Questão 33 — Relação água/cimento e resistência</strong></p>
<p>Investigue a relação entre <code>relacao_a_c</code> e <code>resistencia_mpa</code>, analisando os padrões encontrados e interpretando os resultados considerando o <strong>comportamento esperado do concreto</strong>.</p>
<p><strong>Questão 34 — Evolução da resistência com a idade</strong></p>
<p>Compare a <strong>resistência média dos concretos em diferentes idades</strong> e analise a evolução da resistência com o aumento da idade dos corpos de prova.</p>
<p><strong>Questão 35 — Informações estatísticas relevantes</strong></p>
<p>Selecione e justifique as <strong>cinco informações estatísticas mais importantes</strong> para compor um relatório técnico destinado ao engenheiro responsável.</p>
</section>
<section id="etapa-conclusiva-script-final" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="etapa-conclusiva-script-final"><span class="header-section-number">3.2</span> 🏁 Etapa conclusiva — Script final</h2>
<p>Como etapa conclusiva, desenvolva um <strong>script final em R, organizado e comentado</strong>, contemplando todo o fluxo de trabalho desenvolvido ao longo da atividade.</p>
<p>O script deverá contemplar:</p>
<ol type="1">
<li><strong>Inspeção inicial da base</strong>;</li>
<li><strong>Identificação de problemas e inconsistências</strong>;</li>
<li><strong>Verificação de valores ausentes</strong>;</li>
<li><strong>Verificação e correção de inconsistências nas variáveis</strong>;</li>
<li><strong>Produção de uma versão limpa dos dados</strong>;</li>
<li><strong>Geração de estatísticas descritivas relevantes</strong>;</li>
<li><strong>Criação de pelo menos duas variáveis derivadas</strong>;</li>
<li><strong>Produção de informações úteis para auxiliar o engenheiro responsável pela obra</strong>.</li>
</ol>
<p>O código deverá ser estruturado de forma que <strong>outro engenheiro consiga compreender as etapas realizadas</strong>, permitindo a reprodução das análises e dos resultados obtidos.</p>
<p>Para isso, deverão ser utilizadas, sempre que pertinentes, as ferramentas de <strong>Base R trabalhadas em sala de aula</strong>, incluindo:</p>
<p><code>str()</code>, <code>summary()</code>, <code>subset()</code>, <code>apply()</code>, <code>lapply()</code>, <code>sapply()</code>, <code>ifelse()</code>, <code>for</code>, <code>if</code>, <code>tapply()</code>, <code>aggregate()</code>, <code>split()</code>, <code>with()</code>, <code>by()</code>, <code>within()</code> e <code>ave()</code>.</p>
</section>
</section>
<section id="fundamentação-teórica" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> 📚 Fundamentação teórica</h1>
<p>A <strong>Estatística Descritiva</strong> reúne métodos utilizados para organizar, resumir e apresentar dados, facilitando sua interpretação e permitindo uma compreensão inicial do comportamento de um conjunto de informações. Entre seus principais recursos estão as <strong>medidas de posição</strong>, como a média, e as <strong>medidas de dispersão</strong>, utilizadas para avaliar a variabilidade dos dados <span class="citation" data-cites="batista2024estatistica">(<a href="#ref-batista2024estatistica" role="doc-biblioref">BATISTA, 2024</a>)</span>.</p>
<p>O <strong>R</strong> é uma linguagem de programação e ambiente computacional amplamente utilizado para <strong>análise de dados e cálculos estatísticos</strong>. O <strong>Base R</strong> disponibiliza diversas funções para manipulação, processamento e análise de dados, incluindo <code>summary()</code>, <code>mean()</code>, <code>apply()</code>, <code>lapply()</code> e <code>sapply()</code> <span class="citation" data-cites="batista2023rbasico">(<a href="#ref-batista2023rbasico" role="doc-biblioref">BATISTA e ARTHUR, 2023</a>)</span>.</p>
<p>Neste trabalho, esses conceitos são utilizados como <strong>fundamentação para o desenvolvimento das análises estatísticas e computacionais</strong> apresentadas nas etapas seguintes. A aplicação dessas ferramentas permite transformar uma base de dados inicialmente bruta em informações organizadas, interpretáveis e úteis para o <strong>processo de tomada de decisão na Engenharia Civil</strong>.</p>
</section>
<section id="resultados-e-discussão" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> 🔍 Resultados e Discussão</h1>
<section id="questão-1-importação-dos-dados" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="questão-1-importação-dos-dados"><span class="header-section-number">5.1</span> Questão 1 — Importação dos dados</h2>
<p>A base de dados foi importada para o R utilizando a função <code>read.csv()</code> e armazenada no objeto <code>dados</code>.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Importação da base de dados</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>dados <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"base_de_dados.csv"</span>,</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">header =</span> <span class="cn">TRUE</span>,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">sep =</span> <span class="st">";"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualização das primeiras observações</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dados)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  id_corpo_prova    obra tipo_concreto idade_dias resistencia_mpa cimento_kg_m3
1         CP-001 Bloco A           C35         28            36.3           395
2         CP-002 Bloco A           C30          7            28.4           340
3         CP-003 Bloco C           C30         56            36.1           338
4         CP-004 Bloco A           C40         28            47.2           407
5         CP-005 Bloco B           C25         28            27.9           316
6         CP-006 Bloco B           C40         28            41.5           398
  relacao_a_c abatimento_mm densidade_kg_m3 absorção_agregado_pct
1         0.5           111            2332                  2.30
2        0.54           114            2389                  1.85
3        0.56           106            2427                  1.89
4        0.47           142            2345                  1.97
5        0.61           133            2448                  2.31
6        0.43            98            2324                  0.80</code></pre>
</div>
</div>
<p>O código utilizado foi dividido em duas etapas. Primeiramente, <code>read.csv()</code> realiza a <strong>leitura do arquivo</strong>, enquanto <code>header = TRUE</code> informa que a primeira linha contém os <strong>nomes das variáveis</strong>. O argumento <code>sep = ";"</code> define o <strong>ponto e vírgula como separador das colunas</strong>, conforme a estrutura do arquivo.</p>
<p>Em seguida, <code>head(dados)</code> apresenta as <strong>primeiras observações da base</strong>, permitindo verificar se os dados foram importados e organizados corretamente.</p>
</section>
<section id="questão-2-dimensões-da-base" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="questão-2-dimensões-da-base"><span class="header-section-number">5.2</span> Questão 2 — Dimensões da base</h2>
<p>Para verificar o tamanho da base de dados, foi utilizada a função <code>dim()</code>, que retorna o número de <strong>linhas e colunas</strong> do objeto <code>dados</code>.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Verificação das dimensões da base</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(dados)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 100  10</code></pre>
</div>
</div>
<p>A função <code>dim()</code> apresenta as dimensões no formato <strong>(linhas, colunas)</strong>. Portanto, o primeiro valor corresponde ao número de <strong>observações</strong>, enquanto o segundo representa o número de <strong>variáveis</strong>.</p>
<p>No caso da base analisada, o resultado foi <strong>100 observações e 10 variáveis</strong>, confirmando que a base possui <strong>100 registros de corpos de prova</strong>, distribuídos em 10 características.</p>
</section>
<section id="questão-3-estrutura-da-base-de-dados" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="questão-3-estrutura-da-base-de-dados"><span class="header-section-number">5.3</span> Questão 3 — Estrutura da base de dados</h2>
<p>Para verificar a estrutura da base de dados, foi utilizada a função <code>str()</code>, que permite identificar o número de observações e variáveis, os nomes das colunas e os respectivos tipos de dados.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(dados)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   100 obs. of  10 variables:
 $ id_corpo_prova       : chr  "CP-001" "CP-002" "CP-003" "CP-004" ...
 $ obra                 : chr  "Bloco A" "Bloco A" "Bloco C" "Bloco A" ...
 $ tipo_concreto        : chr  "C35" "C30" "C30" "C40" ...
 $ idade_dias           : int  28 7 56 28 28 28 56 28 14 7 ...
 $ resistencia_mpa      : chr  "36.3" "28.4" "36.1" "47.2" ...
 $ cimento_kg_m3        : chr  "395" "340" "338" "407" ...
 $ relacao_a_c          : chr  "0.5" "0.54" "0.56" "0.47" ...
 $ abatimento_mm        : num  111 114 106 142 133 98 99 116 125 127 ...
 $ densidade_kg_m3      : num  2332 2389 2427 2345 2448 ...
 $ absorção_agregado_pct: num  2.3 1.85 1.89 1.97 2.31 0.8 1.18 1.33 2.92 1.94 ...</code></pre>
</div>
</div>
<p>A análise da estrutura permite verificar como o R interpretou cada variável e identificar possíveis problemas de importação ou classificação. As variáveis quantitativas devem estar armazenadas como numéricas (<strong>“num”</strong> ou <strong>“int”</strong>), enquanto as variáveis qualitativas, como categorias de obra e tipo de concreto, podem ser armazenadas como caracteres (<strong>“chr”</strong>).</p>
<p>Essa verificação é importante antes da realização das análises estatísticas, pois a classificação incorreta de uma variável pode interferir nos cálculos e na interpretação dos resultados.</p>
</section>
<section id="questão-4-resumo-estatístico-da-base-de-dados" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="questão-4-resumo-estatístico-da-base-de-dados"><span class="header-section-number">5.4</span> Questão 4 — Resumo estatístico da base de dados</h2>
<p>Para obter uma visão geral das variáveis presentes na base de dados, foi utilizada a função <code>summary()</code>, que apresenta diferentes informações de acordo com o tipo de variável.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dados)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   id_corpo_prova        obra       tipo_concreto   idade_dias 
 Length   :100    Length   :100   Length   :100   Min.   :  7  
 N.unique :100    N.unique :  5   N.unique :  5   1st Qu.: 14  
 N.blank  :  0    N.blank  :  0   N.blank  :  0   Median : 28  
 Min.nchar:  6    Min.nchar:  7   Min.nchar:  3   Mean   : 28  
 Max.nchar:  6    Max.nchar:  8   Max.nchar:  3   3rd Qu.: 28  
                                                  Max.   :280  
                                                               
  resistencia_mpa   cimento_kg_m3    relacao_a_c  abatimento_mm   
 Length   :100    Length   :100   Length   :100   Min.   :  64.0  
 N.unique : 84    N.unique : 68   N.unique : 25   1st Qu.:  99.5  
 N.blank  :  1    N.blank  :  0   N.blank  :  1   Median : 110.0  
 Min.nchar:  0    Min.nchar:  3   Min.nchar:  0   Mean   : 121.7  
 Max.nchar:  4    Max.nchar:  4   Max.nchar:  4   3rd Qu.: 122.5  
                                                  Max.   :1250.0  
                                                  NAs    :1       
 densidade_kg_m3 absorção_agregado_pct
 Min.   : 238    Min.   : 0.800       
 1st Qu.:2348    1st Qu.: 1.475       
 Median :2374    Median : 1.850       
 Mean   :2351    Mean   : 1.953       
 3rd Qu.:2388    3rd Qu.: 2.110       
 Max.   :2464    Max.   :18.400       
 NAs    :1       NAs    :1            </code></pre>
</div>
</div>
<p>Para as <strong>variáveis quantitativas</strong>, a função apresenta medidas como mínimo, quartis, mediana, média e máximo. Para as <strong>variáveis qualitativas</strong>, são apresentadas as categorias existentes e suas respectivas frequências. Também são disponibilizadas informações sobre valores em branco e características das variáveis de texto.</p>
<p>A tabela abaixo apresenta um resumo dos resultados obtidos por meio dessa função:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 17%">
<col style="width: 58%">
</colgroup>
<thead>
<tr class="header">
<th>Informação apresentada</th>
<th>Tipo de variável</th>
<th>Significado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Length</strong></td>
<td>Qualitativa</td>
<td>Quantidade total de elementos da variável.</td>
</tr>
<tr class="even">
<td><strong>N.unique</strong></td>
<td>Qualitativa</td>
<td>Número de valores ou categorias diferentes.</td>
</tr>
<tr class="odd">
<td><strong>Min.</strong></td>
<td>Quantitativa</td>
<td>Menor valor observado.</td>
</tr>
<tr class="even">
<td><strong>1st Qu.</strong></td>
<td>Quantitativa</td>
<td>Primeiro quartil (25% dos dados).</td>
</tr>
<tr class="odd">
<td><strong>Median</strong></td>
<td>Quantitativa</td>
<td>Mediana (50% dos dados).</td>
</tr>
<tr class="even">
<td><strong>Mean</strong></td>
<td>Quantitativa</td>
<td>Média dos valores.</td>
</tr>
<tr class="odd">
<td><strong>3rd Qu.</strong></td>
<td>Quantitativa</td>
<td>Terceiro quartil (75% dos dados).</td>
</tr>
<tr class="even">
<td><strong>Max.</strong></td>
<td>Quantitativa</td>
<td>Maior valor observado.</td>
</tr>
<tr class="odd">
<td><strong>NA’s</strong></td>
<td>Quantitativa</td>
<td>Quantidade de valores ausentes (<em>missing values</em>).</td>
</tr>
<tr class="even">
<td><strong>n.&nbsp;blank</strong></td>
<td>Qualitativa</td>
<td>Quantidade de valores em branco.</td>
</tr>
<tr class="odd">
<td><strong>mincharn</strong></td>
<td>Qualitativa</td>
<td>Menor número de caracteres encontrados.</td>
</tr>
<tr class="even">
<td><strong>maxcharn</strong></td>
<td>Qualitativa</td>
<td>Maior número de caracteres encontrados.</td>
</tr>
</tbody>
</table>
<p>Dessa forma, o <code>summary()</code> fornece uma visão inicial da estrutura e das características dos dados, permitindo verificar a distribuição das variáveis, suas frequências e a presença de valores ausentes.</p>
</section>
<section id="questão-5-classificação-das-variáveis" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="questão-5-classificação-das-variáveis"><span class="header-section-number">5.5</span> Questão 5 — Classificação das variáveis</h2>
<p>Antes de verificar a classificação realizada pelo R, foram definidos os <strong>tipos esperados para cada variável</strong>, considerando sua natureza e seu significado no contexto do controle tecnológico do concreto. Assim, variáveis que representam categorias ou identificações são consideradas <strong>qualitativas</strong>, enquanto aquelas que representam medidas ou quantidades são consideradas <strong>quantitativas</strong>.</p>
<p>Para verificar como o R reconheceu cada variável, foi utilizada a função <code>sapply()</code> em conjunto com <code>class()</code>.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Verificação do tipo de cada variável</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(dados, class)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       id_corpo_prova                  obra         tipo_concreto 
          "character"           "character"           "character" 
           idade_dias       resistencia_mpa         cimento_kg_m3 
            "integer"           "character"           "character" 
          relacao_a_c         abatimento_mm       densidade_kg_m3 
          "character"             "numeric"             "numeric" 
absorção_agregado_pct 
            "numeric" </code></pre>
</div>
</div>
<p>O resultado obtido foi:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 31%">
<col style="width: 18%">
<col style="width: 31%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th>Variável</th>
<th>Tipo esperado</th>
<th>Tipo reconhecido pelo R</th>
<th>Classificação</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>id_corpo_prova</code></td>
<td>Qualitativa</td>
<td><code>character</code></td>
<td>Qualitativa</td>
</tr>
<tr class="even">
<td><code>obra</code></td>
<td>Qualitativa</td>
<td><code>character</code></td>
<td>Qualitativa</td>
</tr>
<tr class="odd">
<td><code>tipo_concreto</code></td>
<td>Qualitativa</td>
<td><code>character</code></td>
<td>Qualitativa</td>
</tr>
<tr class="even">
<td><code>idade_dias</code></td>
<td>Quantitativa</td>
<td><code>integer</code></td>
<td>Quantitativa</td>
</tr>
<tr class="odd">
<td><code>resistencia_mpa</code></td>
<td>Quantitativa</td>
<td><code>character</code></td>
<td>Qualitativa</td>
</tr>
<tr class="even">
<td><code>cimento_kg_m3</code></td>
<td>Quantitativa</td>
<td><code>character</code></td>
<td>Qualitativa</td>
</tr>
<tr class="odd">
<td><code>relacao_a_c</code></td>
<td>Quantitativa</td>
<td><code>character</code></td>
<td>Qualitativa</td>
</tr>
<tr class="even">
<td><code>abatimento_mm</code></td>
<td>Quantitativa</td>
<td><code>numeric</code></td>
<td>Quantitativa</td>
</tr>
<tr class="odd">
<td><code>densidade_kg_m3</code></td>
<td>Quantitativa</td>
<td><code>numeric</code></td>
<td>Quantitativa</td>
</tr>
<tr class="even">
<td><code>absorção_agregado_pct</code></td>
<td>Quantitativa</td>
<td><code>numeric</code></td>
<td>Quantitativa</td>
</tr>
</tbody>
</table>
<p>A partir da estrutura apresentada pelo R, as variáveis <strong><code>id_corpo_prova</code></strong>, <strong><code>obra</code></strong> e <strong><code>tipo_concreto</code></strong> foram reconhecidas como <code>character</code>, estando de acordo com o esperado para variáveis qualitativas. Já <strong><code>idade_dias</code></strong>, <strong><code>abatimento_mm</code></strong>, <strong><code>densidade_kg_m3</code></strong> e <strong><code>absorção_agregado_pct</code></strong> foram reconhecidas como <code>integer</code> ou <code>numeric</code>, também de acordo com sua natureza quantitativa.</p>
<p>Entretanto, <strong><code>resistencia_mpa</code></strong>, <strong><code>cimento_kg_m3</code></strong> e <strong><code>relacao_a_c</code></strong> são quantitativas por sua natureza, mas foram reconhecidas pelo R como <code>character</code>. Essa divergência pode estar relacionada a <strong>erros de digitação, caracteres inseridos nos valores ou separadores decimais inadequados</strong>, fazendo com que o R interprete essas informações como texto.</p>
<p>Portanto, a estrutura apresentada pelo R permite identificar que essas três variáveis precisarão ser <strong>corrigidas e convertidas para um formato quantitativo</strong> nas etapas posteriores de limpeza da base.</p>
</section>
<section id="questão-6-valores-ausentes-na-base" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="questão-6-valores-ausentes-na-base"><span class="header-section-number">5.6</span> Questão 6 — Valores ausentes na base</h2>
<p>Para verificar a existência de valores ausentes ou registros vazios na base, foram considerados tanto os valores <code>NA</code> quanto os principais padrões utilizados para representar dados não preenchidos: <code>""</code>, <code>" "</code>, <code>"NA"</code>, <code>"N/A"</code>, <code>"-"</code>, <code>"null"</code> e <code>"NULL"</code>.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Padrões considerados como valores ausentes</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>ausentes <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">""</span>, <span class="st">" "</span>, <span class="st">"NA"</span>, <span class="st">"N/A"</span>, <span class="st">"-"</span>, <span class="st">"null"</span>, <span class="st">"NULL"</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Quantidade total de valores ausentes ou vazios</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(dados) <span class="sc">|</span> dados <span class="sc">==</span> <span class="st">""</span> <span class="sc">|</span> dados <span class="sc">==</span> <span class="st">" "</span> <span class="sc">|</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>      dados <span class="sc">==</span> <span class="st">"NA"</span> <span class="sc">|</span> dados <span class="sc">==</span> <span class="st">"N/A"</span> <span class="sc">|</span> dados <span class="sc">==</span> <span class="st">"-"</span> <span class="sc">|</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>      dados <span class="sc">==</span> <span class="st">"null"</span> <span class="sc">|</span> dados <span class="sc">==</span> <span class="st">"NULL"</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5</code></pre>
</div>
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Quantidade por variável</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(dados, <span class="cf">function</span>(x)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(<span class="fu">is.na</span>(x) <span class="sc">|</span> x <span class="sc">%in%</span> ausentes, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       id_corpo_prova                  obra         tipo_concreto 
                    0                     0                     0 
           idade_dias       resistencia_mpa         cimento_kg_m3 
                    0                     1                     0 
          relacao_a_c         abatimento_mm       densidade_kg_m3 
                    1                     1                     1 
absorção_agregado_pct 
                    1 </code></pre>
</div>
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Observações que apresentam valores ausentes ou vazios</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(<span class="fu">apply</span>(dados, <span class="dv">1</span>, <span class="cf">function</span>(x)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">any</span>(<span class="fu">is.na</span>(x) <span class="sc">|</span> x <span class="sc">%in%</span> ausentes)))</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 15 38 77 92 97</code></pre>
</div>
</div>
<p>O primeiro comando contabiliza o <strong>total de valores ausentes ou vazios</strong> encontrados na base. O segundo identifica <strong>em quais variáveis esses registros aparecem</strong>, enquanto o terceiro apresenta <strong>as observações afetadas</strong>.</p>
<p>Dessa forma, a análise não considera apenas os valores <code>NA</code> reconhecidos automaticamente pelo R, mas também registros preenchidos com diferentes formas de indicar ausência de informação.</p>
<section id="investigação-dos-erros-de-preenchimento-e-padronização" class="level3" data-number="5.6.1">
<h3 data-number="5.6.1" class="anchored" data-anchor-id="investigação-dos-erros-de-preenchimento-e-padronização"><span class="header-section-number">5.6.1</span> Investigação dos erros de preenchimento e padronização</h3>
<p>Nesta etapa, foram investigados possíveis <strong>erros de preenchimento e inconsistências de padronização</strong> em todas as células da base. A análise buscou identificar automaticamente diferenças de escrita, caracteres inadequados, espaços desnecessários e formas diferentes de representação dos mesmos valores.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Remoção de espaços desnecessários</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(dados, <span class="cf">function</span>(x) <span class="fu">sum</span>(<span class="fu">grepl</span>(<span class="st">"^ | $"</span>, x)))</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       id_corpo_prova                  obra         tipo_concreto 
                    0                     1                     0 
           idade_dias       resistencia_mpa         cimento_kg_m3 
                    0                     0                     0 
          relacao_a_c         abatimento_mm       densidade_kg_m3 
                    0                     0                     0 
absorção_agregado_pct 
                    0 </code></pre>
</div>
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Identificação de categorias diferentes nas variáveis qualitativas</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(dados<span class="sc">$</span>obra)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Bloco A"  "Bloco C"  "Bloco B"  "Bloco D"  "Bloco B "</code></pre>
</div>
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(dados<span class="sc">$</span>tipo_concreto)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "C35" "C30" "C40" "C25" "c30"</code></pre>
</div>
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Identificação de valores que possuem vírgula decimal</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(dados, <span class="cf">function</span>(x) <span class="fu">sum</span>(<span class="fu">grepl</span>(<span class="st">","</span>, x)))</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       id_corpo_prova                  obra         tipo_concreto 
                    0                     0                     0 
           idade_dias       resistencia_mpa         cimento_kg_m3 
                    0                     2                     0 
          relacao_a_c         abatimento_mm       densidade_kg_m3 
                    1                     0                     0 
absorção_agregado_pct 
                    0 </code></pre>
</div>
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Identificação de valores contendo letras em variáveis quantitativas</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>variaveis_quantitativas <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">"idade_dias"</span>,</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="st">"resistencia_mpa"</span>,</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="st">"cimento_kg_m3"</span>,</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="st">"relacao_a_c"</span>,</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="st">"abatimento_mm"</span>,</span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  <span class="st">"densidade_kg_m3"</span>,</span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">"absorção_agregado_pct"</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(dados[variaveis_quantitativas], <span class="cf">function</span>(x)</span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(<span class="fu">grepl</span>(<span class="st">"[A-Za-z]"</span>, x))</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>           idade_dias       resistencia_mpa         cimento_kg_m3 
                    0                     1                     1 
          relacao_a_c         abatimento_mm       densidade_kg_m3 
                    0                     0                     0 
absorção_agregado_pct 
                    0 </code></pre>
</div>
</div>
<p>A investigação permitiu identificar <strong>erros de preenchimento e diferenças de padronização</strong> nas variáveis da base. Foram encontrados registros com <strong>espaços adicionais</strong>, diferenças de <strong>maiúsculas e minúsculas</strong>, utilização de <strong>vírgula como separador decimal</strong> e presença de <strong>caracteres alfabéticos em variáveis que deveriam conter valores numéricos</strong>.</p>
<p>Essas inconsistências podem fazer com que valores que representam a mesma informação sejam interpretados de maneiras diferentes pelo R. Por isso, os registros identificados deverão ser avaliados e padronizados nas etapas posteriores de tratamento dos dados.</p>
</section>
</section>
<section id="questão-7-valores-potencialmente-incompatíveis" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="questão-7-valores-potencialmente-incompatíveis"><span class="header-section-number">5.7</span> Questão 7 — Valores potencialmente incompatíveis</h2>
<p>Nesta etapa, foram investigados valores que podem ser <strong>incompatíveis ou suspeitos no contexto da Engenharia Civil</strong>. Os critérios utilizados foram baseados, quando aplicável, em referências normativas e, nos demais casos, na identificação de valores que se afastam significativamente do padrão observado na própria base.</p>
<p>Para o <strong>abatimento</strong>, foi considerada a <strong>ABNT NBR 16889:2020</strong>, que estabelece o método para determinação da consistência do concreto pelo abatimento do tronco de cone, em conjunto com as classes de abatimento estabelecidas pela <strong>ABNT NBR 8953:2015</strong> <span class="citation" data-cites="abnt16889 abnt8953">(<a href="#ref-abnt8953" role="doc-biblioref">Associação Brasileira de Normas Técnicas, 2015</a>, <a href="#ref-abnt16889" role="doc-biblioref">2020</a>)</span>.</p>
<p>Para a <strong>resistência à compressão</strong>, foi considerada a <strong>ABNT NBR 5739:2018</strong>, que estabelece o método para determinação da resistência à compressão de corpos de prova cilíndricos de concreto <span class="citation" data-cites="abnt5739">(<a href="#ref-abnt5739" role="doc-biblioref">Associação Brasileira de Normas Técnicas, 2018</a>)</span>. Como a norma não estabelece um intervalo universal de resistência válido para todos os concretos, os valores utilizados na triagem foram definidos a partir do contexto e do padrão observado na própria base.</p>
<p>Para <strong>densidade e absorção</strong>, foi considerada a <strong>ABNT NBR 9778:2005</strong>, que estabelece métodos para determinação da absorção de água, índice de vazios e massa específica de argamassas e concretos endurecidos <span class="citation" data-cites="abnt9778">(<a href="#ref-abnt9778" role="doc-biblioref">Associação Brasileira de Normas Técnicas, 2005</a>)</span>.</p>
<p>Para <strong>idade dos corpos de prova</strong> e <strong>relação água/cimento</strong>, foi realizada uma análise exploratória baseada nos valores observados na própria base, pois esses parâmetros dependem das condições de projeto, dosagem e programa experimental.</p>
<div class="cell">
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Valores potencialmente incompatíveis com o contexto dos dados</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Idade dos corpos de prova</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>dados[dados<span class="sc">$</span>idade_dias <span class="sc">&lt;=</span> <span class="dv">0</span> <span class="sc">|</span> dados<span class="sc">$</span>idade_dias <span class="sc">&gt;</span> <span class="dv">56</span>, ]</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   id_corpo_prova    obra tipo_concreto idade_dias resistencia_mpa
85         CP-085 Bloco A           C30        280            38.3
   cimento_kg_m3 relacao_a_c abatimento_mm densidade_kg_m3
85           342         0.6           141            2377
   absorção_agregado_pct
85                  1.86</code></pre>
</div>
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Resistência à compressão</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>dados[dados<span class="sc">$</span>resistencia_mpa <span class="sc">&lt;</span> <span class="dv">20</span> <span class="sc">|</span> dados<span class="sc">$</span>resistencia_mpa <span class="sc">&gt;</span> <span class="dv">60</span>, ]</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   id_corpo_prova    obra tipo_concreto idade_dias resistencia_mpa
77         CP-077 Bloco D           C25         14            19.0
92         CP-092 Bloco B           C35         14                
   cimento_kg_m3 relacao_a_c abatimento_mm densidade_kg_m3
77           307        0.63           119              NA
92           370        0.47           111            2380
   absorção_agregado_pct
77                  1.38
92                  2.38</code></pre>
</div>
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Abatimento</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>dados[dados<span class="sc">$</span>abatimento_mm <span class="sc">&lt;</span> <span class="dv">10</span> <span class="sc">|</span> dados<span class="sc">$</span>abatimento_mm <span class="sc">&gt;</span> <span class="dv">220</span>, ]</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   id_corpo_prova    obra tipo_concreto idade_dias resistencia_mpa
NA           &lt;NA&gt;    &lt;NA&gt;          &lt;NA&gt;         NA            &lt;NA&gt;
32         CP-032 Bloco D           C35         14            36.6
   cimento_kg_m3 relacao_a_c abatimento_mm densidade_kg_m3
NA          &lt;NA&gt;        &lt;NA&gt;            NA              NA
32           370        0.53          1250            2383
   absorção_agregado_pct
NA                    NA
32                  2.13</code></pre>
</div>
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Densidade</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>dados[dados<span class="sc">$</span>densidade_kg_m3 <span class="sc">&lt;</span> <span class="dv">2000</span> <span class="sc">|</span> dados<span class="sc">$</span>densidade_kg_m3 <span class="sc">&gt;</span> <span class="dv">2600</span>, ]</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   id_corpo_prova    obra tipo_concreto idade_dias resistencia_mpa
53         CP-053 Bloco D           C30         28            27.4
NA           &lt;NA&gt;    &lt;NA&gt;          &lt;NA&gt;         NA            &lt;NA&gt;
   cimento_kg_m3 relacao_a_c abatimento_mm densidade_kg_m3
53           349        0.61            97             238
NA          &lt;NA&gt;        &lt;NA&gt;            NA              NA
   absorção_agregado_pct
53                  1.79
NA                    NA</code></pre>
</div>
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Relação água/cimento</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>dados[dados<span class="sc">$</span>relacao_a_c <span class="sc">&lt;</span> <span class="fl">0.40</span> <span class="sc">|</span> dados<span class="sc">$</span>relacao_a_c <span class="sc">&gt;</span> <span class="fl">0.70</span>, ]</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   id_corpo_prova    obra tipo_concreto idade_dias resistencia_mpa
38         CP-038 Bloco C           C25         28            25.7
45         CP-045 Bloco C           C40         14            42.9
   cimento_kg_m3 relacao_a_c abatimento_mm densidade_kg_m3
38           309                       146            2334
45           407        0,55            76            2381
   absorção_agregado_pct
38                  2.12
45                  2.12</code></pre>
</div>
<details class="code-fold">
<summary>Código</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Absorção</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>dados[dados<span class="sc">$</span><span class="st">`</span><span class="at">absorção_agregado_pct</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">0</span> <span class="sc">|</span> </span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>        dados<span class="sc">$</span><span class="st">`</span><span class="at">absorção_agregado_pct</span><span class="st">`</span> <span class="sc">&gt;</span> <span class="dv">10</span>, ]</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   id_corpo_prova    obra tipo_concreto idade_dias resistencia_mpa
72         CP-072 Bloco B           C40         14            37.3
NA           &lt;NA&gt;    &lt;NA&gt;          &lt;NA&gt;         NA            &lt;NA&gt;
   cimento_kg_m3 relacao_a_c abatimento_mm densidade_kg_m3
72           403        0.48            98            2414
NA          &lt;NA&gt;        &lt;NA&gt;            NA              NA
   absorção_agregado_pct
72                  18.4
NA                    NA</code></pre>
</div>
</div>
<p>Os códigos acima realizam uma <strong>triagem inicial</strong>, permitindo localizar as observações que merecem investigação. Um valor identificado não deve ser automaticamente considerado incorreto, pois pode representar uma condição real de ensaio ou de dosagem.</p>
<p>Na base analisada, esses critérios permitem identificar, entre outros, <strong>idade de 280 dias</strong>, <strong>abatimento de 1250 mm</strong>, <strong>densidade de 238 kg/m³</strong> e <strong>absorção de 18,4%</strong>. Esses valores apresentam grande afastamento em relação aos demais registros e, portanto, devem ser conferidos antes da utilização da base nas análises estatísticas.</p>
<p>Dessa forma, a etapa não consiste simplesmente em excluir valores considerados extremos, mas em <strong>localizar possíveis inconsistências para posterior verificação e tratamento</strong>, preservando inicialmente as informações da base original.</p>
</section>
</section>
<section id="considerações-finais" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> 🧠 Considerações finais</h1>
</section>
<section id="referências" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> 📖 Referências</h1>
<div id="refs" class="references csl-bib-body" data-entry-spacing="0" role="list">
<!-- -->

<div id="ref-abnt9778" class="csl-entry" role="listitem">
ASSOCIAÇÃO BRASILEIRA DE NORMAS TÉCNICAS. <strong>ABNT NBR 9778:2005: Argamassa e concreto endurecidos — Determinação da absorção de água, índice de vazios e massa específica</strong>. Rio de Janeiro: ABNT, 2005.
</div>
<div id="ref-abnt8953" class="csl-entry" role="listitem">
___. <strong>ABNT NBR 8953:2015: Concreto para fins estruturais — Classificação pela massa específica, por grupos de resistência e consistência</strong>. Rio de Janeiro: ABNT, 2015.
</div>
<div id="ref-abnt5739" class="csl-entry" role="listitem">
___. <strong>ABNT NBR 5739:2018: Concreto — Ensaio de compressão de corpos de prova cilíndricos</strong>. Rio de Janeiro: ABNT, 2018.
</div>
<div id="ref-abnt16889" class="csl-entry" role="listitem">
___. <strong>ABNT NBR 16889:2020: Concreto — Determinação da consistência pelo abatimento do tronco de cone</strong>. Rio de Janeiro: ABNT, 2020.
</div>
<div id="ref-batista2024estatistica" class="csl-entry" role="listitem">
BATISTA, B. D. DE O. <strong><a href="https://bendeivide.github.io/book-epaec/">Estatística &amp; Probabilidade aplicada às Engenharias e Ciências</a></strong>. Ouro Branco, MG: [s.n.].
</div>
<div id="ref-batista2023rbasico" class="csl-entry" role="listitem">
BATISTA, B. D. DE O.; ARTHUR, D. <strong><a href="https://bendeivide.github.io/book-eambr01/">R básico: Coleção Estudando o Ambiente R</a></strong>. [s.l: s.n.]. v. 1
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Código fonte</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb39" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co">--- </span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Só mude aqui!!!! </span></span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Marco Antônio e Matheus Villela" </span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Relatório 02 - Aula prática 02" </span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="an">bibliography:</span><span class="co"> referencias.bib </span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a><span class="co"># A partir daqui nao faca alteracoes!!!!! </span></span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a><span class="an">link-citations:</span><span class="co"> true </span></span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a><span class="an">csl:</span><span class="co"> associacao-brasileira-de-normas-tecnicas-ipea.csl </span></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> "&lt;a href='https://bendeivide.github.io/courses/eait/' target='_blank'&gt;Estatística Aplicada a Inovações Tecnológicas (UFSJ)&lt;/a&gt; &lt;/br&gt; &lt;a href='https://bendeivide.github.io' target='_blank'&gt;Prof. Ben Dêivide (DEFIM/CAP/UFSJ)&lt;/a&gt;"</span></span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a><span class="an">include-before-body:</span><span class="co"> header.html</span></span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> now</span></span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a><span class="an">date-format:</span><span class="co"> "DD/MM/YYYY, HH:mm"</span></span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a><span class="an">lang:</span><span class="co"> pt-BR</span></span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-title: "Sumário"      # Define o nome do sumário</span></span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-location: left        # Coloca o sumário no lado esquerdo (opcional)</span></span>
<span id="cb39-19"><a href="#cb39-19" aria-hidden="true" tabindex="-1"></a><span class="co">    number-sections: true</span></span>
<span id="cb39-20"><a href="#cb39-20" aria-hidden="true" tabindex="-1"></a><span class="co">    theme: bootstrap</span></span>
<span id="cb39-21"><a href="#cb39-21" aria-hidden="true" tabindex="-1"></a><span class="co">    #css: styles.css</span></span>
<span id="cb39-22"><a href="#cb39-22" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb39-23"><a href="#cb39-23" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb39-24"><a href="#cb39-24" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span></span>
<span id="cb39-25"><a href="#cb39-25" aria-hidden="true" tabindex="-1"></a><span class="co">  echo: true</span></span>
<span id="cb39-26"><a href="#cb39-26" aria-hidden="true" tabindex="-1"></a><span class="co">  warning: false</span></span>
<span id="cb39-27"><a href="#cb39-27" aria-hidden="true" tabindex="-1"></a><span class="co">  message: false</span></span>
<span id="cb39-28"><a href="#cb39-28" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb39-29"><a href="#cb39-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-30"><a href="#cb39-30" aria-hidden="true" tabindex="-1"></a><span class="fu"># 📌 Introdução</span></span>
<span id="cb39-31"><a href="#cb39-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-32"><a href="#cb39-32" aria-hidden="true" tabindex="-1"></a>No **controle tecnológico do concreto**, a qualidade das decisões técnicas depende diretamente da confiabilidade dos dados coletados em campo e em laboratório. Contudo, na prática profissional, é comum que bases de dados apresentem inconsistências, como **valores ausentes, erros de digitação, padronização inadequada de categorias e registros incompatíveis com a realidade física do concreto**. Esses problemas, quando não tratados adequadamente, podem comprometer as análises estatísticas e levar a interpretações equivocadas.</span>
<span id="cb39-33"><a href="#cb39-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-34"><a href="#cb39-34" aria-hidden="true" tabindex="-1"></a>Esta atividade simula uma situação real em que o engenheiro recebe uma **base de dados bruta contendo 100 registros e 10 variáveis relacionadas ao concreto**. Utilizando a linguagem **R, com ênfase nos recursos do Base R**, o trabalho consiste em **inspecionar, diagnosticar, limpar e explorar os dados**, transformando informações inconsistentes em dados confiáveis para auxiliar na tomada de decisão no contexto da **Engenharia Civil**.</span>
<span id="cb39-35"><a href="#cb39-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-36"><a href="#cb39-36" aria-hidden="true" tabindex="-1"></a><span class="fu"># 🎯 Objetivo geral</span></span>
<span id="cb39-37"><a href="#cb39-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-38"><a href="#cb39-38" aria-hidden="true" tabindex="-1"></a>Inspecionar, diagnosticar, limpar e explorar uma base de dados do **controle tecnológico do concreto** utilizando o **R (Base R)**, transformando dados brutos e inconsistentes em informações confiáveis para a **tomada de decisão técnica no âmbito da Engenharia Civil**.</span>
<span id="cb39-39"><a href="#cb39-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-40"><a href="#cb39-40" aria-hidden="true" tabindex="-1"></a><span class="fu">## Objetivos específicos</span></span>
<span id="cb39-41"><a href="#cb39-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-42"><a href="#cb39-42" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**Conhecer a estrutura da base**, identificando o número de observações, variáveis, tipos de dados e valores ausentes.</span>
<span id="cb39-43"><a href="#cb39-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-44"><a href="#cb39-44" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**Diagnosticar problemas**, como erros de digitação, separadores decimais incorretos, categorias despadronizadas e valores incompatíveis com o contexto da Engenharia Civil.</span>
<span id="cb39-45"><a href="#cb39-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-46"><a href="#cb39-46" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**Padronizar e limpar os dados**, corrigindo variáveis qualitativas e quantitativas, tratando valores ausentes e criando uma versão limpa da base.</span>
<span id="cb39-47"><a href="#cb39-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-48"><a href="#cb39-48" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**Explorar os dados tratados** por meio de estatísticas descritivas e análises agrupadas por obra, tipo de concreto e idade.</span>
<span id="cb39-49"><a href="#cb39-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-50"><a href="#cb39-50" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**Criar variáveis derivadas com interpretação técnica**, como resistência relativa, classificação de desempenho e indicador de desempenho acima da média.</span>
<span id="cb39-51"><a href="#cb39-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-52"><a href="#cb39-52" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**Aplicar funções do Base R**, como <span class="in">`split()`</span>, <span class="in">`lapply()`</span>, <span class="in">`sapply()`</span>, <span class="in">`apply()`</span>, <span class="in">`aggregate()`</span>, <span class="in">`for`</span> e <span class="in">`if`</span>, para o processamento e a análise dos dados.</span>
<span id="cb39-53"><a href="#cb39-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-54"><a href="#cb39-54" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**Responder questões práticas da Engenharia Civil**, como a comparação de desempenho entre blocos e a relação entre diferentes variáveis do concreto.</span>
<span id="cb39-55"><a href="#cb39-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-56"><a href="#cb39-56" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**Documentar e justificar as decisões de limpeza e análise**, garantindo maior rastreabilidade e reprodutibilidade dos procedimentos realizados.</span>
<span id="cb39-57"><a href="#cb39-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-58"><a href="#cb39-58" aria-hidden="true" tabindex="-1"></a><span class="ss">* </span>**Desenvolver um script organizado e comentado** que execute todo o fluxo de trabalho, desde a inspeção inicial até a geração de estatísticas e variáveis derivadas.</span>
<span id="cb39-59"><a href="#cb39-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-60"><a href="#cb39-60" aria-hidden="true" tabindex="-1"></a><span class="fu"># ⚙️ Metodologia</span></span>
<span id="cb39-61"><a href="#cb39-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-62"><a href="#cb39-62" aria-hidden="true" tabindex="-1"></a>A metodologia adotada neste trabalho consiste no **processamento completo de uma base de dados do controle tecnológico do concreto**, utilizando a linguagem **R**, com ênfase nos recursos disponíveis no **Base R**.</span>
<span id="cb39-63"><a href="#cb39-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-64"><a href="#cb39-64" aria-hidden="true" tabindex="-1"></a>O fluxo de trabalho segue uma sequência lógica composta pelas etapas de:</span>
<span id="cb39-65"><a href="#cb39-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-66"><a href="#cb39-66" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Importação dos dados**;</span>
<span id="cb39-67"><a href="#cb39-67" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Inspeção inicial da base**;</span>
<span id="cb39-68"><a href="#cb39-68" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Diagnóstico de inconsistências**;</span>
<span id="cb39-69"><a href="#cb39-69" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**Limpeza e padronização dos dados**;</span>
<span id="cb39-70"><a href="#cb39-70" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>**Tratamento dos valores ausentes**;</span>
<span id="cb39-71"><a href="#cb39-71" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>**Exploração estatística**;</span>
<span id="cb39-72"><a href="#cb39-72" aria-hidden="true" tabindex="-1"></a><span class="ss">7. </span>**Criação de variáveis derivadas**;</span>
<span id="cb39-73"><a href="#cb39-73" aria-hidden="true" tabindex="-1"></a><span class="ss">8. </span>**Aplicação de funções de processamento**;</span>
<span id="cb39-74"><a href="#cb39-74" aria-hidden="true" tabindex="-1"></a><span class="ss">9. </span>**Interpretação dos resultados sob a perspectiva da Engenharia Civil**.</span>
<span id="cb39-75"><a href="#cb39-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-76"><a href="#cb39-76" aria-hidden="true" tabindex="-1"></a>As etapas foram organizadas em **35 questões**, que orientam o desenvolvimento progressivo da atividade.</span>
<span id="cb39-77"><a href="#cb39-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-78"><a href="#cb39-78" aria-hidden="true" tabindex="-1"></a><span class="fu">## 📋 Etapas de desenvolvimento</span></span>
<span id="cb39-79"><a href="#cb39-79" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-80"><a href="#cb39-80" aria-hidden="true" tabindex="-1"></a>**Questão 01 — Importação dos dados**</span>
<span id="cb39-81"><a href="#cb39-81" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-82"><a href="#cb39-82" aria-hidden="true" tabindex="-1"></a>Importe a base de dados para o R e atribua-a ao objeto <span class="in">`dados`</span>, verificando a correta importação.</span>
<span id="cb39-83"><a href="#cb39-83" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-84"><a href="#cb39-84" aria-hidden="true" tabindex="-1"></a>**Questão 02 — Dimensões da base**</span>
<span id="cb39-85"><a href="#cb39-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-86"><a href="#cb39-86" aria-hidden="true" tabindex="-1"></a>Determine as dimensões da base, identificando o número de **observações (linhas)** e **variáveis (colunas)**.</span>
<span id="cb39-87"><a href="#cb39-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-88"><a href="#cb39-88" aria-hidden="true" tabindex="-1"></a>**Questão 03 — Estrutura da base**</span>
<span id="cb39-89"><a href="#cb39-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-90"><a href="#cb39-90" aria-hidden="true" tabindex="-1"></a>Apresente a estrutura completa da base utilizando a função <span class="in">`str()`</span> e analise detalhadamente o resultado obtido.</span>
<span id="cb39-91"><a href="#cb39-91" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-92"><a href="#cb39-92" aria-hidden="true" tabindex="-1"></a>**Questão 04 — Resumo estatístico**</span>
<span id="cb39-93"><a href="#cb39-93" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-94"><a href="#cb39-94" aria-hidden="true" tabindex="-1"></a>Gere um resumo estatístico das variáveis com a função <span class="in">`summary()`</span> e identifique informações que merecem atenção.</span>
<span id="cb39-95"><a href="#cb39-95" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-96"><a href="#cb39-96" aria-hidden="true" tabindex="-1"></a>**Questão 05 — Classificação das variáveis**</span>
<span id="cb39-97"><a href="#cb39-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-98"><a href="#cb39-98" aria-hidden="true" tabindex="-1"></a>Classifique as variáveis em **quantitativas** e **qualitativas**, com base na estrutura apresentada pelo R.</span>
<span id="cb39-99"><a href="#cb39-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-100"><a href="#cb39-100" aria-hidden="true" tabindex="-1"></a>**Questão 06 — Valores ausentes**</span>
<span id="cb39-101"><a href="#cb39-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-102"><a href="#cb39-102" aria-hidden="true" tabindex="-1"></a>Verifique a existência de **valores ausentes (*missing values*)**, identificando a quantidade, as variáveis e as observações afetadas.</span>
<span id="cb39-103"><a href="#cb39-103" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-104"><a href="#cb39-104" aria-hidden="true" tabindex="-1"></a>**Questão 07 — Valores incompatíveis**</span>
<span id="cb39-105"><a href="#cb39-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-106"><a href="#cb39-106" aria-hidden="true" tabindex="-1"></a>Verifique valores incompatíveis com o contexto da Engenharia Civil nas variáveis <span class="in">`idade_dias`</span>, <span class="in">`resistencia_mpa`</span>, <span class="in">`abatimento_mm`</span>, <span class="in">`densidade_kg_m3`</span>, <span class="in">`relacao_a_c`</span> e <span class="in">`absorção_agregado_pct`</span>, criando códigos para a localização das observações problemáticas.</span>
<span id="cb39-107"><a href="#cb39-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-108"><a href="#cb39-108" aria-hidden="true" tabindex="-1"></a>**Questão 08 — Erros de digitação**</span>
<span id="cb39-109"><a href="#cb39-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-110"><a href="#cb39-110" aria-hidden="true" tabindex="-1"></a>Localize possíveis **erros de digitação** e apresente os registros completos das observações afetadas.</span>
<span id="cb39-111"><a href="#cb39-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-112"><a href="#cb39-112" aria-hidden="true" tabindex="-1"></a>**Questão 09 — Padronização da variável `obra`**</span>
<span id="cb39-113"><a href="#cb39-113" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-114"><a href="#cb39-114" aria-hidden="true" tabindex="-1"></a>Verifique a padronização das categorias da variável <span class="in">`obra`</span> e identifique possíveis inconsistências.</span>
<span id="cb39-115"><a href="#cb39-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-116"><a href="#cb39-116" aria-hidden="true" tabindex="-1"></a>**Questão 10 — Padronização da variável `tipo_concreto`**</span>
<span id="cb39-117"><a href="#cb39-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-118"><a href="#cb39-118" aria-hidden="true" tabindex="-1"></a>Verifique a padronização das categorias da variável <span class="in">`tipo_concreto`</span> e identifique categorias que representam o mesmo tipo de concreto com **grafias diferentes**.</span>
<span id="cb39-119"><a href="#cb39-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-120"><a href="#cb39-120" aria-hidden="true" tabindex="-1"></a>**Questão 11 — Reavaliação dos tipos**</span>
<span id="cb39-121"><a href="#cb39-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-122"><a href="#cb39-122" aria-hidden="true" tabindex="-1"></a>Reavalie os tipos das variáveis após a identificação dos problemas e reflita sobre como **um único valor digitado incorretamente pode alterar a interpretação de uma variável inteira pelo R**.</span>
<span id="cb39-123"><a href="#cb39-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-124"><a href="#cb39-124" aria-hidden="true" tabindex="-1"></a>**Questão 12 — Cópia da base original**</span>
<span id="cb39-125"><a href="#cb39-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-126"><a href="#cb39-126" aria-hidden="true" tabindex="-1"></a>Crie uma cópia da base original chamada <span class="in">`dados_limpos`</span> e discuta a importância de **preservar a base original** durante o processo de tratamento dos dados.</span>
<span id="cb39-127"><a href="#cb39-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-128"><a href="#cb39-128" aria-hidden="true" tabindex="-1"></a>**Questão 13 — Correção das variáveis qualitativas**</span>
<span id="cb39-129"><a href="#cb39-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-130"><a href="#cb39-130" aria-hidden="true" tabindex="-1"></a>Corrija os problemas encontrados nas variáveis qualitativas, **padronizando suas categorias**.</span>
<span id="cb39-131"><a href="#cb39-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-132"><a href="#cb39-132" aria-hidden="true" tabindex="-1"></a>**Questão 14 — Conversão das variáveis quantitativas**</span>
<span id="cb39-133"><a href="#cb39-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-134"><a href="#cb39-134" aria-hidden="true" tabindex="-1"></a>Converta para o tipo adequado as variáveis que deveriam ser quantitativas e verifique se a conversão foi realizada corretamente.</span>
<span id="cb39-135"><a href="#cb39-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-136"><a href="#cb39-136" aria-hidden="true" tabindex="-1"></a>**Questão 15 — Tratamento dos valores ausentes**</span>
<span id="cb39-137"><a href="#cb39-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-138"><a href="#cb39-138" aria-hidden="true" tabindex="-1"></a>Identifique os valores ausentes e discuta os procedimentos mais adequados para cada situação, considerando **exclusão, substituição, manutenção do `NA` ou consulta à fonte original**. Justifique tecnicamente as decisões adotadas.</span>
<span id="cb39-139"><a href="#cb39-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-140"><a href="#cb39-140" aria-hidden="true" tabindex="-1"></a>**Questão 16 — Reavaliação da base limpa**</span>
<span id="cb39-141"><a href="#cb39-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-142"><a href="#cb39-142" aria-hidden="true" tabindex="-1"></a>Reavalie a estrutura (<span class="in">`str()`</span>) e o resumo (<span class="in">`summary()`</span>) da base limpa e compare os resultados obtidos com aqueles observados na **base original**.</span>
<span id="cb39-143"><a href="#cb39-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-144"><a href="#cb39-144" aria-hidden="true" tabindex="-1"></a>**Questão 17 — Resistência média**</span>
<span id="cb39-145"><a href="#cb39-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-146"><a href="#cb39-146" aria-hidden="true" tabindex="-1"></a>Calcule a **resistência média à compressão** dos corpos de prova globalmente e por bloco da obra, tipo de concreto e idade do corpo de prova.</span>
<span id="cb39-147"><a href="#cb39-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-148"><a href="#cb39-148" aria-hidden="true" tabindex="-1"></a>**Questão 18 — Maior e menor resistência média**</span>
<span id="cb39-149"><a href="#cb39-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-150"><a href="#cb39-150" aria-hidden="true" tabindex="-1"></a>Identifique o bloco da obra que apresenta a **maior e a menor resistência média**, apresentando os códigos utilizados para essa identificação.</span>
<span id="cb39-151"><a href="#cb39-151" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-152"><a href="#cb39-152" aria-hidden="true" tabindex="-1"></a>**Questão 19 — Resistência por classe de concreto**</span>
<span id="cb39-153"><a href="#cb39-153" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-154"><a href="#cb39-154" aria-hidden="true" tabindex="-1"></a>Calcule a resistência média para cada classe de concreto (**C25, C30, C35 e C40**) e identifique a classe que apresenta a **maior resistência média**.</span>
<span id="cb39-155"><a href="#cb39-155" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-156"><a href="#cb39-156" aria-hidden="true" tabindex="-1"></a>**Questão 20 — Aplicação da função `aggregate()`**</span>
<span id="cb39-157"><a href="#cb39-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-158"><a href="#cb39-158" aria-hidden="true" tabindex="-1"></a>Utilize a função <span class="in">`aggregate()`</span> para obter a média das variáveis <span class="in">`resistencia_mpa`</span>, <span class="in">`cimento_kg_m3`</span>, <span class="in">`relacao_a_c`</span>, <span class="in">`abatimento_mm`</span> e <span class="in">`densidade_kg_m3`</span> para cada tipo de concreto e interprete os resultados.</span>
<span id="cb39-159"><a href="#cb39-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-160"><a href="#cb39-160" aria-hidden="true" tabindex="-1"></a>**Questão 21 — Resistência relativa**</span>
<span id="cb39-161"><a href="#cb39-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-162"><a href="#cb39-162" aria-hidden="true" tabindex="-1"></a>Crie a variável <span class="in">`resistencia_relativa`</span>, representando a razão entre a **resistência observada** e uma **resistência de referência associada à classe do concreto**, e explique como a referência foi definida.</span>
<span id="cb39-163"><a href="#cb39-163" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-164"><a href="#cb39-164" aria-hidden="true" tabindex="-1"></a>**Questão 22 — Classificação do desempenho**</span>
<span id="cb39-165"><a href="#cb39-165" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-166"><a href="#cb39-166" aria-hidden="true" tabindex="-1"></a>Crie a variável <span class="in">`classificacao`</span>, classificando os corpos de prova segundo um critério relacionado à resistência, definindo e justificando tecnicamente os critérios utilizados.</span>
<span id="cb39-167"><a href="#cb39-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-168"><a href="#cb39-168" aria-hidden="true" tabindex="-1"></a>**Questão 23 — Desempenho acima da média**</span>
<span id="cb39-169"><a href="#cb39-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-170"><a href="#cb39-170" aria-hidden="true" tabindex="-1"></a>Crie a variável <span class="in">`acima_media`</span>, indicando se a resistência do corpo de prova está **acima ou abaixo da resistência média de seu respectivo tipo de concreto**, utilizando os valores <span class="in">`TRUE`</span> ou <span class="in">`FALSE`</span>.</span>
<span id="cb39-171"><a href="#cb39-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-172"><a href="#cb39-172" aria-hidden="true" tabindex="-1"></a>**Questão 24 — Aplicação da função `split()`**</span>
<span id="cb39-173"><a href="#cb39-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-174"><a href="#cb39-174" aria-hidden="true" tabindex="-1"></a>Utilize a função <span class="in">`split()`</span> para dividir a base de dados de acordo com a variável <span class="in">`tipo_concreto`</span> e conte o **número de observações em cada grupo**.</span>
<span id="cb39-175"><a href="#cb39-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-176"><a href="#cb39-176" aria-hidden="true" tabindex="-1"></a>**Questão 25 — Aplicação da função `lapply()`**</span>
<span id="cb39-177"><a href="#cb39-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-178"><a href="#cb39-178" aria-hidden="true" tabindex="-1"></a>Utilizando a estrutura criada com <span class="in">`split()`</span>, calcule a **resistência média de cada tipo de concreto** utilizando a função <span class="in">`lapply()`</span>.</span>
<span id="cb39-179"><a href="#cb39-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-180"><a href="#cb39-180" aria-hidden="true" tabindex="-1"></a>**Questão 26 — Aplicação da função `sapply()`**</span>
<span id="cb39-181"><a href="#cb39-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-182"><a href="#cb39-182" aria-hidden="true" tabindex="-1"></a>Repita a operação utilizando <span class="in">`sapply()`</span> e explique a diferença entre os resultados produzidos por <span class="in">`lapply()`</span> e <span class="in">`sapply()`</span>.</span>
<span id="cb39-183"><a href="#cb39-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-184"><a href="#cb39-184" aria-hidden="true" tabindex="-1"></a>**Questão 27 — Aplicação da função `apply()` para médias**</span>
<span id="cb39-185"><a href="#cb39-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-186"><a href="#cb39-186" aria-hidden="true" tabindex="-1"></a>Selecione as variáveis quantitativas relacionadas às propriedades do concreto e utilize a função <span class="in">`apply()`</span> para calcular a **média de cada variável**.</span>
<span id="cb39-187"><a href="#cb39-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-188"><a href="#cb39-188" aria-hidden="true" tabindex="-1"></a>**Questão 28 — Aplicação da função `apply()` por observação**</span>
<span id="cb39-189"><a href="#cb39-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-190"><a href="#cb39-190" aria-hidden="true" tabindex="-1"></a>Utilize a função <span class="in">`apply()`</span> para obter, para cada observação, uma **medida resumo envolvendo as variáveis quantitativas selecionadas** e discuta a interpretação física dessa medida.</span>
<span id="cb39-191"><a href="#cb39-191" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-192"><a href="#cb39-192" aria-hidden="true" tabindex="-1"></a>**Questão 29 — Aplicação de `for` e `if`**</span>
<span id="cb39-193"><a href="#cb39-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-194"><a href="#cb39-194" aria-hidden="true" tabindex="-1"></a>Utilizando <span class="in">`for`</span> e <span class="in">`if`</span> — **sem utilizar `ifelse()`** — percorra as 100 observações e identifique os corpos de prova cuja resistência está acima da **resistência média de sua respectiva classe de concreto**.</span>
<span id="cb39-195"><a href="#cb39-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-196"><a href="#cb39-196" aria-hidden="true" tabindex="-1"></a>**Questão 30 — Abordagem vetorizada**</span>
<span id="cb39-197"><a href="#cb39-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-198"><a href="#cb39-198" aria-hidden="true" tabindex="-1"></a>Repita a questão anterior utilizando uma **abordagem vetorizada** e compare as duas soluções quanto à simplicidade, legibilidade e eficiência, justificando sua análise.</span>
<span id="cb39-199"><a href="#cb39-199" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-200"><a href="#cb39-200" aria-hidden="true" tabindex="-1"></a>**Questão 31 — Comparação entre blocos**</span>
<span id="cb39-201"><a href="#cb39-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-202"><a href="#cb39-202" aria-hidden="true" tabindex="-1"></a>Verifique descritivamente a afirmação:</span>
<span id="cb39-203"><a href="#cb39-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-204"><a href="#cb39-204" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **"Os concretos utilizados no Bloco C apresentam desempenho superior aos utilizados nos demais blocos."**</span></span>
<span id="cb39-205"><a href="#cb39-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-206"><a href="#cb39-206" aria-hidden="true" tabindex="-1"></a>Realize a análise **sem utilizar teste de hipótese**.</span>
<span id="cb39-207"><a href="#cb39-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-208"><a href="#cb39-208" aria-hidden="true" tabindex="-1"></a>**Questão 32 — Consumo de cimento e resistência**</span>
<span id="cb39-209"><a href="#cb39-209" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-210"><a href="#cb39-210" aria-hidden="true" tabindex="-1"></a>Investigue a afirmação:</span>
<span id="cb39-211"><a href="#cb39-211" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-212"><a href="#cb39-212" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; **"Quanto maior o consumo de cimento, maior tende a ser a resistência do concreto."**</span></span>
<span id="cb39-213"><a href="#cb39-213" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-214"><a href="#cb39-214" aria-hidden="true" tabindex="-1"></a>Identifique as variáveis que devem ser analisadas conjuntamente para avaliar essa relação.</span>
<span id="cb39-215"><a href="#cb39-215" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-216"><a href="#cb39-216" aria-hidden="true" tabindex="-1"></a>**Questão 33 — Relação água/cimento e resistência**</span>
<span id="cb39-217"><a href="#cb39-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-218"><a href="#cb39-218" aria-hidden="true" tabindex="-1"></a>Investigue a relação entre <span class="in">`relacao_a_c`</span> e <span class="in">`resistencia_mpa`</span>, analisando os padrões encontrados e interpretando os resultados considerando o **comportamento esperado do concreto**.</span>
<span id="cb39-219"><a href="#cb39-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-220"><a href="#cb39-220" aria-hidden="true" tabindex="-1"></a>**Questão 34 — Evolução da resistência com a idade**</span>
<span id="cb39-221"><a href="#cb39-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-222"><a href="#cb39-222" aria-hidden="true" tabindex="-1"></a>Compare a **resistência média dos concretos em diferentes idades** e analise a evolução da resistência com o aumento da idade dos corpos de prova.</span>
<span id="cb39-223"><a href="#cb39-223" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-224"><a href="#cb39-224" aria-hidden="true" tabindex="-1"></a>**Questão 35 — Informações estatísticas relevantes**</span>
<span id="cb39-225"><a href="#cb39-225" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-226"><a href="#cb39-226" aria-hidden="true" tabindex="-1"></a>Selecione e justifique as **cinco informações estatísticas mais importantes** para compor um relatório técnico destinado ao engenheiro responsável.</span>
<span id="cb39-227"><a href="#cb39-227" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-228"><a href="#cb39-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-229"><a href="#cb39-229" aria-hidden="true" tabindex="-1"></a><span class="fu">## 🏁 Etapa conclusiva — Script final</span></span>
<span id="cb39-230"><a href="#cb39-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-231"><a href="#cb39-231" aria-hidden="true" tabindex="-1"></a>Como etapa conclusiva, desenvolva um **script final em R, organizado e comentado**, contemplando todo o fluxo de trabalho desenvolvido ao longo da atividade.</span>
<span id="cb39-232"><a href="#cb39-232" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-233"><a href="#cb39-233" aria-hidden="true" tabindex="-1"></a>O script deverá contemplar:</span>
<span id="cb39-234"><a href="#cb39-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-235"><a href="#cb39-235" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**Inspeção inicial da base**;</span>
<span id="cb39-236"><a href="#cb39-236" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Identificação de problemas e inconsistências**;</span>
<span id="cb39-237"><a href="#cb39-237" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Verificação de valores ausentes**;</span>
<span id="cb39-238"><a href="#cb39-238" aria-hidden="true" tabindex="-1"></a><span class="ss">4. </span>**Verificação e correção de inconsistências nas variáveis**;</span>
<span id="cb39-239"><a href="#cb39-239" aria-hidden="true" tabindex="-1"></a><span class="ss">5. </span>**Produção de uma versão limpa dos dados**;</span>
<span id="cb39-240"><a href="#cb39-240" aria-hidden="true" tabindex="-1"></a><span class="ss">6. </span>**Geração de estatísticas descritivas relevantes**;</span>
<span id="cb39-241"><a href="#cb39-241" aria-hidden="true" tabindex="-1"></a><span class="ss">7. </span>**Criação de pelo menos duas variáveis derivadas**;</span>
<span id="cb39-242"><a href="#cb39-242" aria-hidden="true" tabindex="-1"></a><span class="ss">8. </span>**Produção de informações úteis para auxiliar o engenheiro responsável pela obra**.</span>
<span id="cb39-243"><a href="#cb39-243" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-244"><a href="#cb39-244" aria-hidden="true" tabindex="-1"></a>O código deverá ser estruturado de forma que **outro engenheiro consiga compreender as etapas realizadas**, permitindo a reprodução das análises e dos resultados obtidos.</span>
<span id="cb39-245"><a href="#cb39-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-246"><a href="#cb39-246" aria-hidden="true" tabindex="-1"></a>Para isso, deverão ser utilizadas, sempre que pertinentes, as ferramentas de **Base R trabalhadas em sala de aula**, incluindo:</span>
<span id="cb39-247"><a href="#cb39-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-248"><a href="#cb39-248" aria-hidden="true" tabindex="-1"></a><span class="in">`str()`</span>, <span class="in">`summary()`</span>, <span class="in">`subset()`</span>, <span class="in">`apply()`</span>, <span class="in">`lapply()`</span>, <span class="in">`sapply()`</span>, <span class="in">`ifelse()`</span>, <span class="in">`for`</span>, <span class="in">`if`</span>, <span class="in">`tapply()`</span>, <span class="in">`aggregate()`</span>, <span class="in">`split()`</span>, <span class="in">`with()`</span>, <span class="in">`by()`</span>, <span class="in">`within()`</span> e <span class="in">`ave()`</span>.</span>
<span id="cb39-249"><a href="#cb39-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-250"><a href="#cb39-250" aria-hidden="true" tabindex="-1"></a><span class="fu"># 📚 Fundamentação teórica</span></span>
<span id="cb39-251"><a href="#cb39-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-252"><a href="#cb39-252" aria-hidden="true" tabindex="-1"></a>A **Estatística Descritiva** reúne métodos utilizados para organizar, resumir e apresentar dados, facilitando sua interpretação e permitindo uma compreensão inicial do comportamento de um conjunto de informações. Entre seus principais recursos estão as **medidas de posição**, como a média, e as **medidas de dispersão**, utilizadas para avaliar a variabilidade dos dados <span class="co">[</span><span class="ot">@batista2024estatistica</span><span class="co">]</span>.</span>
<span id="cb39-253"><a href="#cb39-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-254"><a href="#cb39-254" aria-hidden="true" tabindex="-1"></a>O **R** é uma linguagem de programação e ambiente computacional amplamente utilizado para **análise de dados e cálculos estatísticos**. O **Base R** disponibiliza diversas funções para manipulação, processamento e análise de dados, incluindo <span class="in">`summary()`</span>, <span class="in">`mean()`</span>, <span class="in">`apply()`</span>, <span class="in">`lapply()`</span> e <span class="in">`sapply()`</span> <span class="co">[</span><span class="ot">@batista2023rbasico</span><span class="co">]</span>.</span>
<span id="cb39-255"><a href="#cb39-255" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-256"><a href="#cb39-256" aria-hidden="true" tabindex="-1"></a>Neste trabalho, esses conceitos são utilizados como **fundamentação para o desenvolvimento das análises estatísticas e computacionais** apresentadas nas etapas seguintes. A aplicação dessas ferramentas permite transformar uma base de dados inicialmente bruta em informações organizadas, interpretáveis e úteis para o **processo de tomada de decisão na Engenharia Civil**.</span>
<span id="cb39-257"><a href="#cb39-257" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-258"><a href="#cb39-258" aria-hidden="true" tabindex="-1"></a><span class="fu"># 🔍 Resultados e Discussão</span></span>
<span id="cb39-259"><a href="#cb39-259" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-260"><a href="#cb39-260" aria-hidden="true" tabindex="-1"></a><span class="fu">## Questão 1 — Importação dos dados</span></span>
<span id="cb39-261"><a href="#cb39-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-262"><a href="#cb39-262" aria-hidden="true" tabindex="-1"></a>A base de dados foi importada para o R utilizando a função <span class="in">`read.csv()`</span> e armazenada no objeto <span class="in">`dados`</span>.</span>
<span id="cb39-263"><a href="#cb39-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-266"><a href="#cb39-266" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-267"><a href="#cb39-267" aria-hidden="true" tabindex="-1"></a><span class="co"># Importação da base de dados</span></span>
<span id="cb39-268"><a href="#cb39-268" aria-hidden="true" tabindex="-1"></a>dados <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"base_de_dados.csv"</span>,</span>
<span id="cb39-269"><a href="#cb39-269" aria-hidden="true" tabindex="-1"></a>                  <span class="at">header =</span> <span class="cn">TRUE</span>,</span>
<span id="cb39-270"><a href="#cb39-270" aria-hidden="true" tabindex="-1"></a>                  <span class="at">sep =</span> <span class="st">";"</span>)</span>
<span id="cb39-271"><a href="#cb39-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-272"><a href="#cb39-272" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualização das primeiras observações</span></span>
<span id="cb39-273"><a href="#cb39-273" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dados)</span>
<span id="cb39-274"><a href="#cb39-274" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-275"><a href="#cb39-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-276"><a href="#cb39-276" aria-hidden="true" tabindex="-1"></a>O código utilizado foi dividido em duas etapas. Primeiramente, <span class="in">`read.csv()`</span> realiza a **leitura do arquivo**, enquanto `header = TRUE` informa que a primeira linha contém os **nomes das variáveis**. O argumento `sep = ";"` define o **ponto e vírgula como separador das colunas**, conforme a estrutura do arquivo.</span>
<span id="cb39-277"><a href="#cb39-277" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-278"><a href="#cb39-278" aria-hidden="true" tabindex="-1"></a>Em seguida, <span class="in">`head(dados)`</span> apresenta as **primeiras observações da base**, permitindo verificar se os dados foram importados e organizados corretamente.</span>
<span id="cb39-279"><a href="#cb39-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-280"><a href="#cb39-280" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-281"><a href="#cb39-281" aria-hidden="true" tabindex="-1"></a><span class="fu">## Questão 2 — Dimensões da base</span></span>
<span id="cb39-282"><a href="#cb39-282" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-283"><a href="#cb39-283" aria-hidden="true" tabindex="-1"></a>Para verificar o tamanho da base de dados, foi utilizada a função <span class="in">`dim()`</span>, que retorna o número de **linhas e colunas** do objeto <span class="in">`dados`</span>.</span>
<span id="cb39-284"><a href="#cb39-284" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-287"><a href="#cb39-287" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-288"><a href="#cb39-288" aria-hidden="true" tabindex="-1"></a><span class="co"># Verificação das dimensões da base</span></span>
<span id="cb39-289"><a href="#cb39-289" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(dados)</span>
<span id="cb39-290"><a href="#cb39-290" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-291"><a href="#cb39-291" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-292"><a href="#cb39-292" aria-hidden="true" tabindex="-1"></a>A função <span class="in">`dim()`</span> apresenta as dimensões no formato **(linhas, colunas)**. Portanto, o primeiro valor corresponde ao número de **observações**, enquanto o segundo representa o número de **variáveis**.</span>
<span id="cb39-293"><a href="#cb39-293" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-294"><a href="#cb39-294" aria-hidden="true" tabindex="-1"></a>No caso da base analisada, o resultado foi **100 observações e 10 variáveis**, confirmando que a base possui **100 registros de corpos de prova**, distribuídos em 10 características.</span>
<span id="cb39-295"><a href="#cb39-295" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-296"><a href="#cb39-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-297"><a href="#cb39-297" aria-hidden="true" tabindex="-1"></a><span class="fu">## Questão 3 — Estrutura da base de dados</span></span>
<span id="cb39-298"><a href="#cb39-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-299"><a href="#cb39-299" aria-hidden="true" tabindex="-1"></a>Para verificar a estrutura da base de dados, foi utilizada a função <span class="in">`str()`</span>, que permite identificar o número de observações e variáveis, os nomes das colunas e os respectivos tipos de dados.</span>
<span id="cb39-300"><a href="#cb39-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-303"><a href="#cb39-303" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-304"><a href="#cb39-304" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(dados)</span>
<span id="cb39-305"><a href="#cb39-305" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-306"><a href="#cb39-306" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-307"><a href="#cb39-307" aria-hidden="true" tabindex="-1"></a>A análise da estrutura permite verificar como o R interpretou cada variável e identificar possíveis problemas de importação ou classificação. As variáveis quantitativas devem estar armazenadas como numéricas (**"num"** ou **"int"**), enquanto as variáveis qualitativas, como categorias de obra e tipo de concreto, podem ser armazenadas como caracteres (**"chr"**). </span>
<span id="cb39-308"><a href="#cb39-308" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-309"><a href="#cb39-309" aria-hidden="true" tabindex="-1"></a>Essa verificação é importante antes da realização das análises estatísticas, pois a classificação incorreta de uma variável pode interferir nos cálculos e na interpretação dos resultados.</span>
<span id="cb39-310"><a href="#cb39-310" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-311"><a href="#cb39-311" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-312"><a href="#cb39-312" aria-hidden="true" tabindex="-1"></a><span class="fu">## Questão 4 — Resumo estatístico da base de dados</span></span>
<span id="cb39-313"><a href="#cb39-313" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-314"><a href="#cb39-314" aria-hidden="true" tabindex="-1"></a>Para obter uma visão geral das variáveis presentes na base de dados, foi utilizada a função <span class="in">`summary()`</span>, que apresenta diferentes informações de acordo com o tipo de variável.</span>
<span id="cb39-315"><a href="#cb39-315" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-318"><a href="#cb39-318" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-319"><a href="#cb39-319" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dados)</span>
<span id="cb39-320"><a href="#cb39-320" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-321"><a href="#cb39-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-322"><a href="#cb39-322" aria-hidden="true" tabindex="-1"></a>Para as **variáveis quantitativas**, a função apresenta medidas como mínimo, quartis, mediana, média e máximo. Para as **variáveis qualitativas**, são apresentadas as categorias existentes e suas respectivas frequências. Também são disponibilizadas informações sobre valores em branco e características das variáveis de texto.</span>
<span id="cb39-323"><a href="#cb39-323" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-324"><a href="#cb39-324" aria-hidden="true" tabindex="-1"></a>A tabela abaixo apresenta um resumo dos resultados obtidos por meio dessa função:</span>
<span id="cb39-325"><a href="#cb39-325" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-326"><a href="#cb39-326" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-327"><a href="#cb39-327" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Informação apresentada <span class="pp">|</span> Tipo de variável <span class="pp">|</span> Significado                                           <span class="pp">|</span></span>
<span id="cb39-328"><a href="#cb39-328" aria-hidden="true" tabindex="-1"></a><span class="pp">| ----------------------</span> <span class="pp">| ----------------</span> <span class="pp">| -----------------------------------------------------</span> <span class="pp">|</span></span>
<span id="cb39-329"><a href="#cb39-329" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Length**             <span class="pp">|</span> Qualitativa     <span class="pp">|</span> Quantidade total de elementos da variável.            <span class="pp">|</span></span>
<span id="cb39-330"><a href="#cb39-330" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **N.unique**           <span class="pp">|</span> Qualitativa      <span class="pp">|</span> Número de valores ou categorias diferentes.           <span class="pp">|</span></span>
<span id="cb39-331"><a href="#cb39-331" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Min.**               <span class="pp">|</span> Quantitativa     <span class="pp">|</span> Menor valor observado.                                <span class="pp">|</span></span>
<span id="cb39-332"><a href="#cb39-332" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **1st Qu.**            <span class="pp">|</span> Quantitativa     <span class="pp">|</span> Primeiro quartil (25% dos dados).                     <span class="pp">|</span></span>
<span id="cb39-333"><a href="#cb39-333" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Median**             <span class="pp">|</span> Quantitativa     <span class="pp">|</span> Mediana (50% dos dados).                              <span class="pp">|</span></span>
<span id="cb39-334"><a href="#cb39-334" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Mean**               <span class="pp">|</span> Quantitativa     <span class="pp">|</span> Média dos valores.                                    <span class="pp">|</span></span>
<span id="cb39-335"><a href="#cb39-335" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **3rd Qu.**            <span class="pp">|</span> Quantitativa     <span class="pp">|</span> Terceiro quartil (75% dos dados).                     <span class="pp">|</span></span>
<span id="cb39-336"><a href="#cb39-336" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **Max.**               <span class="pp">|</span> Quantitativa     <span class="pp">|</span> Maior valor observado.                                <span class="pp">|</span></span>
<span id="cb39-337"><a href="#cb39-337" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **NA's**               <span class="pp">|</span> Quantitativa     <span class="pp">|</span> Quantidade de valores ausentes (*missing values*).    <span class="pp">|</span></span>
<span id="cb39-338"><a href="#cb39-338" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **n. blank**           <span class="pp">|</span> Qualitativa      <span class="pp">|</span> Quantidade de valores em branco.                      <span class="pp">|</span></span>
<span id="cb39-339"><a href="#cb39-339" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **mincharn**           <span class="pp">|</span> Qualitativa      <span class="pp">|</span> Menor número de caracteres encontrados.               <span class="pp">|</span></span>
<span id="cb39-340"><a href="#cb39-340" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> **maxcharn**           <span class="pp">|</span> Qualitativa      <span class="pp">|</span> Maior número de caracteres encontrados.               <span class="pp">|</span></span>
<span id="cb39-341"><a href="#cb39-341" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-342"><a href="#cb39-342" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-343"><a href="#cb39-343" aria-hidden="true" tabindex="-1"></a>Dessa forma, o <span class="in">`summary()`</span> fornece uma visão inicial da estrutura e das características dos dados, permitindo verificar a distribuição das variáveis, suas frequências e a presença de valores ausentes.</span>
<span id="cb39-344"><a href="#cb39-344" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-345"><a href="#cb39-345" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-346"><a href="#cb39-346" aria-hidden="true" tabindex="-1"></a><span class="fu">## Questão 5 — Classificação das variáveis</span></span>
<span id="cb39-347"><a href="#cb39-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-348"><a href="#cb39-348" aria-hidden="true" tabindex="-1"></a>Antes de verificar a classificação realizada pelo R, foram definidos os **tipos esperados para cada variável**, considerando sua natureza e seu significado no contexto do controle tecnológico do concreto. Assim, variáveis que representam categorias ou identificações são consideradas **qualitativas**, enquanto aquelas que representam medidas ou quantidades são consideradas **quantitativas**.</span>
<span id="cb39-349"><a href="#cb39-349" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-350"><a href="#cb39-350" aria-hidden="true" tabindex="-1"></a>Para verificar como o R reconheceu cada variável, foi utilizada a função <span class="in">`sapply()`</span> em conjunto com <span class="in">`class()`</span>.</span>
<span id="cb39-351"><a href="#cb39-351" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-354"><a href="#cb39-354" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-355"><a href="#cb39-355" aria-hidden="true" tabindex="-1"></a><span class="co"># Verificação do tipo de cada variável</span></span>
<span id="cb39-356"><a href="#cb39-356" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(dados, class)</span>
<span id="cb39-357"><a href="#cb39-357" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-358"><a href="#cb39-358" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-359"><a href="#cb39-359" aria-hidden="true" tabindex="-1"></a>O resultado obtido foi:</span>
<span id="cb39-360"><a href="#cb39-360" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-361"><a href="#cb39-361" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Variável                <span class="pp">|</span> Tipo esperado <span class="pp">|</span> Tipo reconhecido pelo R <span class="pp">|</span> Classificação <span class="pp">|</span></span>
<span id="cb39-362"><a href="#cb39-362" aria-hidden="true" tabindex="-1"></a><span class="pp">| -----------------------</span> <span class="pp">| -------------</span> <span class="pp">| -----------------------</span> <span class="pp">| -------------</span> <span class="pp">|</span></span>
<span id="cb39-363"><a href="#cb39-363" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`id_corpo_prova`</span>        <span class="pp">|</span> Qualitativa   <span class="pp">|</span> <span class="in">`character`</span>             <span class="pp">|</span> Qualitativa   <span class="pp">|</span></span>
<span id="cb39-364"><a href="#cb39-364" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`obra`</span>                  <span class="pp">|</span> Qualitativa   <span class="pp">|</span> <span class="in">`character`</span>             <span class="pp">|</span> Qualitativa   <span class="pp">|</span></span>
<span id="cb39-365"><a href="#cb39-365" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`tipo_concreto`</span>         <span class="pp">|</span> Qualitativa   <span class="pp">|</span> <span class="in">`character`</span>             <span class="pp">|</span> Qualitativa   <span class="pp">|</span></span>
<span id="cb39-366"><a href="#cb39-366" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`idade_dias`</span>            <span class="pp">|</span> Quantitativa  <span class="pp">|</span> <span class="in">`integer`</span>               <span class="pp">|</span> Quantitativa  <span class="pp">|</span></span>
<span id="cb39-367"><a href="#cb39-367" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`resistencia_mpa`</span>       <span class="pp">|</span> Quantitativa  <span class="pp">|</span> <span class="in">`character`</span>             <span class="pp">|</span> Qualitativa  <span class="pp">|</span></span>
<span id="cb39-368"><a href="#cb39-368" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`cimento_kg_m3`</span>         <span class="pp">|</span> Quantitativa  <span class="pp">|</span> <span class="in">`character`</span>             <span class="pp">|</span> Qualitativa  <span class="pp">|</span></span>
<span id="cb39-369"><a href="#cb39-369" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`relacao_a_c`</span>           <span class="pp">|</span> Quantitativa  <span class="pp">|</span> <span class="in">`character`</span>             <span class="pp">|</span> Qualitativa  <span class="pp">|</span></span>
<span id="cb39-370"><a href="#cb39-370" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`abatimento_mm`</span>         <span class="pp">|</span> Quantitativa  <span class="pp">|</span> <span class="in">`numeric`</span>               <span class="pp">|</span> Quantitativa  <span class="pp">|</span></span>
<span id="cb39-371"><a href="#cb39-371" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`densidade_kg_m3`</span>       <span class="pp">|</span> Quantitativa  <span class="pp">|</span> <span class="in">`numeric`</span>               <span class="pp">|</span> Quantitativa  <span class="pp">|</span></span>
<span id="cb39-372"><a href="#cb39-372" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> <span class="in">`absorção_agregado_pct`</span> <span class="pp">|</span> Quantitativa  <span class="pp">|</span> <span class="in">`numeric`</span>               <span class="pp">|</span> Quantitativa  <span class="pp">|</span></span>
<span id="cb39-373"><a href="#cb39-373" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-374"><a href="#cb39-374" aria-hidden="true" tabindex="-1"></a>A partir da estrutura apresentada pelo R, as variáveis **`id_corpo_prova`**, **`obra`** e **`tipo_concreto`** foram reconhecidas como `character`, estando de acordo com o esperado para variáveis qualitativas. Já **`idade_dias`**, **`abatimento_mm`**, **`densidade_kg_m3`** e **`absorção_agregado_pct`** foram reconhecidas como <span class="in">`integer`</span> ou <span class="in">`numeric`</span>, também de acordo com sua natureza quantitativa.</span>
<span id="cb39-375"><a href="#cb39-375" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-376"><a href="#cb39-376" aria-hidden="true" tabindex="-1"></a>Entretanto, **`resistencia_mpa`**, **`cimento_kg_m3`** e **`relacao_a_c`** são quantitativas por sua natureza, mas foram reconhecidas pelo R como `character`. Essa divergência pode estar relacionada a **erros de digitação, caracteres inseridos nos valores ou separadores decimais inadequados**, fazendo com que o R interprete essas informações como texto.</span>
<span id="cb39-377"><a href="#cb39-377" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-378"><a href="#cb39-378" aria-hidden="true" tabindex="-1"></a>Portanto, a estrutura apresentada pelo R permite identificar que essas três variáveis precisarão ser **corrigidas e convertidas para um formato quantitativo** nas etapas posteriores de limpeza da base.</span>
<span id="cb39-379"><a href="#cb39-379" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-380"><a href="#cb39-380" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-381"><a href="#cb39-381" aria-hidden="true" tabindex="-1"></a><span class="fu">## Questão 6 — Valores ausentes na base</span></span>
<span id="cb39-382"><a href="#cb39-382" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-383"><a href="#cb39-383" aria-hidden="true" tabindex="-1"></a>Para verificar a existência de valores ausentes ou registros vazios na base, foram considerados tanto os valores <span class="in">`NA`</span> quanto os principais padrões utilizados para representar dados não preenchidos: <span class="in">`""`</span>, <span class="in">`" "`</span>, <span class="in">`"NA"`</span>, <span class="in">`"N/A"`</span>, <span class="in">`"-"`</span>, <span class="in">`"null"`</span> e <span class="in">`"NULL"`</span>.</span>
<span id="cb39-384"><a href="#cb39-384" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-387"><a href="#cb39-387" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-388"><a href="#cb39-388" aria-hidden="true" tabindex="-1"></a><span class="co"># Padrões considerados como valores ausentes</span></span>
<span id="cb39-389"><a href="#cb39-389" aria-hidden="true" tabindex="-1"></a>ausentes <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">""</span>, <span class="st">" "</span>, <span class="st">"NA"</span>, <span class="st">"N/A"</span>, <span class="st">"-"</span>, <span class="st">"null"</span>, <span class="st">"NULL"</span>)</span>
<span id="cb39-390"><a href="#cb39-390" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-391"><a href="#cb39-391" aria-hidden="true" tabindex="-1"></a><span class="co"># Quantidade total de valores ausentes ou vazios</span></span>
<span id="cb39-392"><a href="#cb39-392" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(dados) <span class="sc">|</span> dados <span class="sc">==</span> <span class="st">""</span> <span class="sc">|</span> dados <span class="sc">==</span> <span class="st">" "</span> <span class="sc">|</span></span>
<span id="cb39-393"><a href="#cb39-393" aria-hidden="true" tabindex="-1"></a>      dados <span class="sc">==</span> <span class="st">"NA"</span> <span class="sc">|</span> dados <span class="sc">==</span> <span class="st">"N/A"</span> <span class="sc">|</span> dados <span class="sc">==</span> <span class="st">"-"</span> <span class="sc">|</span></span>
<span id="cb39-394"><a href="#cb39-394" aria-hidden="true" tabindex="-1"></a>      dados <span class="sc">==</span> <span class="st">"null"</span> <span class="sc">|</span> dados <span class="sc">==</span> <span class="st">"NULL"</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb39-395"><a href="#cb39-395" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-396"><a href="#cb39-396" aria-hidden="true" tabindex="-1"></a><span class="co"># Quantidade por variável</span></span>
<span id="cb39-397"><a href="#cb39-397" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(dados, <span class="cf">function</span>(x)</span>
<span id="cb39-398"><a href="#cb39-398" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(<span class="fu">is.na</span>(x) <span class="sc">|</span> x <span class="sc">%in%</span> ausentes, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb39-399"><a href="#cb39-399" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-400"><a href="#cb39-400" aria-hidden="true" tabindex="-1"></a><span class="co"># Observações que apresentam valores ausentes ou vazios</span></span>
<span id="cb39-401"><a href="#cb39-401" aria-hidden="true" tabindex="-1"></a><span class="fu">which</span>(<span class="fu">apply</span>(dados, <span class="dv">1</span>, <span class="cf">function</span>(x)</span>
<span id="cb39-402"><a href="#cb39-402" aria-hidden="true" tabindex="-1"></a>  <span class="fu">any</span>(<span class="fu">is.na</span>(x) <span class="sc">|</span> x <span class="sc">%in%</span> ausentes)))</span>
<span id="cb39-403"><a href="#cb39-403" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-404"><a href="#cb39-404" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-405"><a href="#cb39-405" aria-hidden="true" tabindex="-1"></a>O primeiro comando contabiliza o **total de valores ausentes ou vazios** encontrados na base. O segundo identifica **em quais variáveis esses registros aparecem**, enquanto o terceiro apresenta **as observações afetadas**.</span>
<span id="cb39-406"><a href="#cb39-406" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-407"><a href="#cb39-407" aria-hidden="true" tabindex="-1"></a>Dessa forma, a análise não considera apenas os valores <span class="in">`NA`</span> reconhecidos automaticamente pelo R, mas também registros preenchidos com diferentes formas de indicar ausência de informação.</span>
<span id="cb39-408"><a href="#cb39-408" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-409"><a href="#cb39-409" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-410"><a href="#cb39-410" aria-hidden="true" tabindex="-1"></a><span class="fu">### Investigação dos erros de preenchimento e padronização</span></span>
<span id="cb39-411"><a href="#cb39-411" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-412"><a href="#cb39-412" aria-hidden="true" tabindex="-1"></a>Nesta etapa, foram investigados possíveis **erros de preenchimento e inconsistências de padronização** em todas as células da base. A análise buscou identificar automaticamente diferenças de escrita, caracteres inadequados, espaços desnecessários e formas diferentes de representação dos mesmos valores.</span>
<span id="cb39-413"><a href="#cb39-413" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-416"><a href="#cb39-416" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-417"><a href="#cb39-417" aria-hidden="true" tabindex="-1"></a><span class="co"># Remoção de espaços desnecessários</span></span>
<span id="cb39-418"><a href="#cb39-418" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(dados, <span class="cf">function</span>(x) <span class="fu">sum</span>(<span class="fu">grepl</span>(<span class="st">"^ | $"</span>, x)))</span>
<span id="cb39-419"><a href="#cb39-419" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-420"><a href="#cb39-420" aria-hidden="true" tabindex="-1"></a><span class="co"># Identificação de categorias diferentes nas variáveis qualitativas</span></span>
<span id="cb39-421"><a href="#cb39-421" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(dados<span class="sc">$</span>obra)</span>
<span id="cb39-422"><a href="#cb39-422" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(dados<span class="sc">$</span>tipo_concreto)</span>
<span id="cb39-423"><a href="#cb39-423" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-424"><a href="#cb39-424" aria-hidden="true" tabindex="-1"></a><span class="co"># Identificação de valores que possuem vírgula decimal</span></span>
<span id="cb39-425"><a href="#cb39-425" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(dados, <span class="cf">function</span>(x) <span class="fu">sum</span>(<span class="fu">grepl</span>(<span class="st">","</span>, x)))</span>
<span id="cb39-426"><a href="#cb39-426" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-427"><a href="#cb39-427" aria-hidden="true" tabindex="-1"></a><span class="co"># Identificação de valores contendo letras em variáveis quantitativas</span></span>
<span id="cb39-428"><a href="#cb39-428" aria-hidden="true" tabindex="-1"></a>variaveis_quantitativas <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb39-429"><a href="#cb39-429" aria-hidden="true" tabindex="-1"></a>  <span class="st">"idade_dias"</span>,</span>
<span id="cb39-430"><a href="#cb39-430" aria-hidden="true" tabindex="-1"></a>  <span class="st">"resistencia_mpa"</span>,</span>
<span id="cb39-431"><a href="#cb39-431" aria-hidden="true" tabindex="-1"></a>  <span class="st">"cimento_kg_m3"</span>,</span>
<span id="cb39-432"><a href="#cb39-432" aria-hidden="true" tabindex="-1"></a>  <span class="st">"relacao_a_c"</span>,</span>
<span id="cb39-433"><a href="#cb39-433" aria-hidden="true" tabindex="-1"></a>  <span class="st">"abatimento_mm"</span>,</span>
<span id="cb39-434"><a href="#cb39-434" aria-hidden="true" tabindex="-1"></a>  <span class="st">"densidade_kg_m3"</span>,</span>
<span id="cb39-435"><a href="#cb39-435" aria-hidden="true" tabindex="-1"></a>  <span class="st">"absorção_agregado_pct"</span></span>
<span id="cb39-436"><a href="#cb39-436" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-437"><a href="#cb39-437" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-438"><a href="#cb39-438" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(dados[variaveis_quantitativas], <span class="cf">function</span>(x)</span>
<span id="cb39-439"><a href="#cb39-439" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(<span class="fu">grepl</span>(<span class="st">"[A-Za-z]"</span>, x))</span>
<span id="cb39-440"><a href="#cb39-440" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-441"><a href="#cb39-441" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-442"><a href="#cb39-442" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-443"><a href="#cb39-443" aria-hidden="true" tabindex="-1"></a>A investigação permitiu identificar **erros de preenchimento e diferenças de padronização** nas variáveis da base. Foram encontrados registros com **espaços adicionais**, diferenças de **maiúsculas e minúsculas**, utilização de **vírgula como separador decimal** e presença de **caracteres alfabéticos em variáveis que deveriam conter valores numéricos**.</span>
<span id="cb39-444"><a href="#cb39-444" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-445"><a href="#cb39-445" aria-hidden="true" tabindex="-1"></a>Essas inconsistências podem fazer com que valores que representam a mesma informação sejam interpretados de maneiras diferentes pelo R. Por isso, os registros identificados deverão ser avaliados e padronizados nas etapas posteriores de tratamento dos dados.</span>
<span id="cb39-446"><a href="#cb39-446" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-447"><a href="#cb39-447" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-448"><a href="#cb39-448" aria-hidden="true" tabindex="-1"></a><span class="fu">## Questão 7 — Valores potencialmente incompatíveis</span></span>
<span id="cb39-449"><a href="#cb39-449" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-450"><a href="#cb39-450" aria-hidden="true" tabindex="-1"></a>Nesta etapa, foram investigados valores que podem ser **incompatíveis ou suspeitos no contexto da Engenharia Civil**. Os critérios utilizados foram baseados, quando aplicável, em referências normativas e, nos demais casos, na identificação de valores que se afastam significativamente do padrão observado na própria base.</span>
<span id="cb39-451"><a href="#cb39-451" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-452"><a href="#cb39-452" aria-hidden="true" tabindex="-1"></a>Para o **abatimento**, foi considerada a **ABNT NBR 16889:2020**, que estabelece o método para determinação da consistência do concreto pelo abatimento do tronco de cone, em conjunto com as classes de abatimento estabelecidas pela **ABNT NBR 8953:2015** <span class="co">[</span><span class="ot">@abnt16889; @abnt8953</span><span class="co">]</span>.</span>
<span id="cb39-453"><a href="#cb39-453" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-454"><a href="#cb39-454" aria-hidden="true" tabindex="-1"></a>Para a **resistência à compressão**, foi considerada a **ABNT NBR 5739:2018**, que estabelece o método para determinação da resistência à compressão de corpos de prova cilíndricos de concreto <span class="co">[</span><span class="ot">@abnt5739</span><span class="co">]</span>. Como a norma não estabelece um intervalo universal de resistência válido para todos os concretos, os valores utilizados na triagem foram definidos a partir do contexto e do padrão observado na própria base.</span>
<span id="cb39-455"><a href="#cb39-455" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-456"><a href="#cb39-456" aria-hidden="true" tabindex="-1"></a>Para **densidade e absorção**, foi considerada a **ABNT NBR 9778:2005**, que estabelece métodos para determinação da absorção de água, índice de vazios e massa específica de argamassas e concretos endurecidos <span class="co">[</span><span class="ot">@abnt9778</span><span class="co">]</span>.</span>
<span id="cb39-457"><a href="#cb39-457" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-458"><a href="#cb39-458" aria-hidden="true" tabindex="-1"></a>Para **idade dos corpos de prova** e **relação água/cimento**, foi realizada uma análise exploratória baseada nos valores observados na própria base, pois esses parâmetros dependem das condições de projeto, dosagem e programa experimental.</span>
<span id="cb39-459"><a href="#cb39-459" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-462"><a href="#cb39-462" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb39-463"><a href="#cb39-463" aria-hidden="true" tabindex="-1"></a><span class="co"># Valores potencialmente incompatíveis com o contexto dos dados</span></span>
<span id="cb39-464"><a href="#cb39-464" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-465"><a href="#cb39-465" aria-hidden="true" tabindex="-1"></a><span class="co"># Idade dos corpos de prova</span></span>
<span id="cb39-466"><a href="#cb39-466" aria-hidden="true" tabindex="-1"></a>dados[dados<span class="sc">$</span>idade_dias <span class="sc">&lt;=</span> <span class="dv">0</span> <span class="sc">|</span> dados<span class="sc">$</span>idade_dias <span class="sc">&gt;</span> <span class="dv">56</span>, ]</span>
<span id="cb39-467"><a href="#cb39-467" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-468"><a href="#cb39-468" aria-hidden="true" tabindex="-1"></a><span class="co"># Resistência à compressão</span></span>
<span id="cb39-469"><a href="#cb39-469" aria-hidden="true" tabindex="-1"></a>dados[dados<span class="sc">$</span>resistencia_mpa <span class="sc">&lt;</span> <span class="dv">20</span> <span class="sc">|</span> dados<span class="sc">$</span>resistencia_mpa <span class="sc">&gt;</span> <span class="dv">60</span>, ]</span>
<span id="cb39-470"><a href="#cb39-470" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-471"><a href="#cb39-471" aria-hidden="true" tabindex="-1"></a><span class="co"># Abatimento</span></span>
<span id="cb39-472"><a href="#cb39-472" aria-hidden="true" tabindex="-1"></a>dados[dados<span class="sc">$</span>abatimento_mm <span class="sc">&lt;</span> <span class="dv">10</span> <span class="sc">|</span> dados<span class="sc">$</span>abatimento_mm <span class="sc">&gt;</span> <span class="dv">220</span>, ]</span>
<span id="cb39-473"><a href="#cb39-473" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-474"><a href="#cb39-474" aria-hidden="true" tabindex="-1"></a><span class="co"># Densidade</span></span>
<span id="cb39-475"><a href="#cb39-475" aria-hidden="true" tabindex="-1"></a>dados[dados<span class="sc">$</span>densidade_kg_m3 <span class="sc">&lt;</span> <span class="dv">2000</span> <span class="sc">|</span> dados<span class="sc">$</span>densidade_kg_m3 <span class="sc">&gt;</span> <span class="dv">2600</span>, ]</span>
<span id="cb39-476"><a href="#cb39-476" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-477"><a href="#cb39-477" aria-hidden="true" tabindex="-1"></a><span class="co"># Relação água/cimento</span></span>
<span id="cb39-478"><a href="#cb39-478" aria-hidden="true" tabindex="-1"></a>dados[dados<span class="sc">$</span>relacao_a_c <span class="sc">&lt;</span> <span class="fl">0.40</span> <span class="sc">|</span> dados<span class="sc">$</span>relacao_a_c <span class="sc">&gt;</span> <span class="fl">0.70</span>, ]</span>
<span id="cb39-479"><a href="#cb39-479" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-480"><a href="#cb39-480" aria-hidden="true" tabindex="-1"></a><span class="co"># Absorção</span></span>
<span id="cb39-481"><a href="#cb39-481" aria-hidden="true" tabindex="-1"></a>dados[dados<span class="sc">$</span><span class="st">`</span><span class="at">absorção_agregado_pct</span><span class="st">`</span> <span class="sc">&lt;</span> <span class="dv">0</span> <span class="sc">|</span> </span>
<span id="cb39-482"><a href="#cb39-482" aria-hidden="true" tabindex="-1"></a>        dados<span class="sc">$</span><span class="st">`</span><span class="at">absorção_agregado_pct</span><span class="st">`</span> <span class="sc">&gt;</span> <span class="dv">10</span>, ]</span>
<span id="cb39-483"><a href="#cb39-483" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb39-484"><a href="#cb39-484" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-485"><a href="#cb39-485" aria-hidden="true" tabindex="-1"></a>Os códigos acima realizam uma **triagem inicial**, permitindo localizar as observações que merecem investigação. Um valor identificado não deve ser automaticamente considerado incorreto, pois pode representar uma condição real de ensaio ou de dosagem.</span>
<span id="cb39-486"><a href="#cb39-486" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-487"><a href="#cb39-487" aria-hidden="true" tabindex="-1"></a>Na base analisada, esses critérios permitem identificar, entre outros, **idade de 280 dias**, **abatimento de 1250 mm**, **densidade de 238 kg/m³** e **absorção de 18,4%**. Esses valores apresentam grande afastamento em relação aos demais registros e, portanto, devem ser conferidos antes da utilização da base nas análises estatísticas.</span>
<span id="cb39-488"><a href="#cb39-488" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-489"><a href="#cb39-489" aria-hidden="true" tabindex="-1"></a>Dessa forma, a etapa não consiste simplesmente em excluir valores considerados extremos, mas em **localizar possíveis inconsistências para posterior verificação e tratamento**, preservando inicialmente as informações da base original.</span>
<span id="cb39-490"><a href="#cb39-490" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-491"><a href="#cb39-491" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-492"><a href="#cb39-492" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-493"><a href="#cb39-493" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-494"><a href="#cb39-494" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-495"><a href="#cb39-495" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-496"><a href="#cb39-496" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-497"><a href="#cb39-497" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-498"><a href="#cb39-498" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-499"><a href="#cb39-499" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-500"><a href="#cb39-500" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-501"><a href="#cb39-501" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-502"><a href="#cb39-502" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-503"><a href="#cb39-503" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-504"><a href="#cb39-504" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-505"><a href="#cb39-505" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-506"><a href="#cb39-506" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-507"><a href="#cb39-507" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-508"><a href="#cb39-508" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-509"><a href="#cb39-509" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-510"><a href="#cb39-510" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-511"><a href="#cb39-511" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-512"><a href="#cb39-512" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-513"><a href="#cb39-513" aria-hidden="true" tabindex="-1"></a><span class="fu"># 🧠 Considerações finais</span></span>
<span id="cb39-514"><a href="#cb39-514" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-515"><a href="#cb39-515" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-516"><a href="#cb39-516" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-517"><a href="#cb39-517" aria-hidden="true" tabindex="-1"></a><span class="fu"># 📖 Referências</span></span>
<span id="cb39-518"><a href="#cb39-518" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-519"><a href="#cb39-519" aria-hidden="true" tabindex="-1"></a>::: {#refs}</span>
</code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




</body></html>